services:
  q-mongodb:
    image: mongo:7.0
    container_name: quant-mongodb
    restart: unless-stopped
    networks:
      - internal
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - mongodb-data:/data/db
    command: ["mongod", "--auth"]
    healthcheck:
      test: |
        mongosh --eval 'db.adminCommand("ping")' \
        --host localhost:27017 \
        --username ${MONGODB_USERNAME} \
        --password ${MONGODB_PASSWORD} \
        --authenticationDatabase admin
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  q-backend:
    image: "${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}"
    container_name: quant-backend
    build:
      context: ./backend
    restart: unless-stopped
    networks:
      - public
      - internal
    environment:
      DUCKDB_PATH: /app/data/market_data.duckdb
    volumes:
      - ./data:/app/data
    depends_on:
      - q-mongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  q-frontend:
    image: "${DOCKER_IMAGE_FRONTEND?Variable not set}:${TAG-latest}"
    container_name: quant-frontend
    restart: unless-stopped
    networks:
      - public

networks:
  public:
    external: true
  internal:
    driver: bridge

volumes:
  mongodb-data:
