
services:
  q-mongodb:
    image: mongo:7.0
    container_name: q-mongodb
    restart: unless-stopped
    networks:
      - internal
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - "27019:27017"
    volumes:
      - mongodb-data:/data/db
    command: ["mongod", "--auth"]
    healthcheck:
      test: |
        mongosh --eval 'db.adminCommand("ping")' \
        --host localhost:27017 \
        --username ${MONGODB_USERNAME} \
        --password ${MONGODB_PASSWORD} \
        --authenticationDatabase admin
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  data-service:
    build: .
    container_name: q-data-service
    restart: unless-stopped
    networks:
      - public
      - internal
    env_file: .env.local
    environment:
      DUCKDB_PATH: /app/data/market_data.duckdb
    ports:
      - "8501:8000"
    volumes:
      - ./data:/app/data
    depends_on:
      - q-mongodb
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]

networks:
  public:
    external: true
  internal:
    driver: bridge

volumes:
  mongodb-data:
