"""
Market data API schemas package
시장 데이터 API 스키마 패키지
"""

# Base schemas
from .base import (
    BaseResponse,
    ErrorResponse,
    DataResponse,
    BulkDataResponse,
    PaginatedResponse,
    PaginationParams,
    PaginationInfo,
    DateRangeParams,
    SymbolParams,
    MultiSymbolParams,
    SortParams,
    FilterParams,
    DataQualityInfo,
    CacheInfo,
    MetadataInfo,
    RefreshDataRequest,
    BulkSymbolRequest,
    HistoricalDataRequest,
    PriceData,
    FinancialMetrics,
    SentimentData,
)

# Stock schemas
from .stock import (
    # Request schemas
    DailyPriceRequest,
    IntradayPriceRequest,
    QuoteRequest,
    BulkQuoteRequest,
    DividendRequest,
    SplitRequest,
    StockSearchRequest,
    BatchStockRequest,
    # Response data models
    DailyPriceData,
    IntradayPriceData,
    QuoteData,
    DividendData,
    SplitData,
    StockOverviewData,
    StockSearchData,
    MarketStatusData,
    BatchStockStatus,
    # Response schemas
    DailyPriceResponse,
    DailyPriceListResponse,
    IntradayPriceResponse,
    IntradayPriceListResponse,
    QuoteResponse,
    BulkQuoteResponse,
    DividendListResponse,
    SplitListResponse,
    StockOverviewResponse,
    StockSearchResponse,
    MarketStatusResponse,
    BatchStockResponse,
)

# Fundamental schemas
from .fundamental import (
    # Request schemas
    CompanyOverviewRequest,
    FinancialStatementRequest,
    EarningsRequest,
    BulkFundamentalRequest,
    PeerComparisonRequest,
    # Response data models
    CompanyOverviewData,
    IncomeStatementData,
    BalanceSheetData,
    CashFlowData,
    EarningsData,
    FundamentalAnalysisData,
    PeerComparisonData,
    SectorAnalysisData,
    # Response schemas
    CompanyOverviewResponse,
    IncomeStatementListResponse,
    BalanceSheetListResponse,
    CashFlowListResponse,
    EarningsListResponse,
    FundamentalAnalysisResponse,
    PeerComparisonResponse,
    SectorAnalysisResponse,
)

# Economic indicator schemas
from .economic_indicator import (
    # Request schemas
    EconomicIndicatorRequest,
    BulkEconomicIndicatorRequest,
    GDPRequest,
    InflationRequest,
    InterestRateRequest,
    # Response data models
    EconomicIndicatorData,
    GDPData,
    InflationData,
    InterestRateData,
    EmploymentData,
    ManufacturingData,
    ConsumerSentimentData,
    EconomicOverviewData,
    # Response schemas
    EconomicIndicatorListResponse,
    GDPListResponse,
    InflationListResponse,
    InterestRateListResponse,
    EmploymentListResponse,
    ManufacturingListResponse,
    ConsumerSentimentListResponse,
    EconomicOverviewResponse,
)

# Intelligence schemas
from .intelligence import (
    # Request schemas
    NewsSentimentRequest,
    NewsArticleRequest,
    AnalystRatingRequest,
    SocialSentimentRequest,
    MarketMoodRequest,
    OptionFlowRequest,
    SentimentAlertRequest,
    # Response data models
    NewsSentimentData,
    NewsArticleData,
    AnalystRatingData,
    SocialSentimentData,
    MarketMoodData,
    OptionFlowData,
    IntelligenceOverviewData,
    SentimentAlertData,
    # Response schemas
    NewsSentimentResponse,
    NewsArticleListResponse,
    AnalystRatingListResponse,
    SocialSentimentListResponse,
    MarketMoodResponse,
    OptionFlowListResponse,
    IntelligenceOverviewResponse,
    SentimentAlertResponse,
)


__all__ = [
    # Base schemas
    "BaseResponse",
    "ErrorResponse",
    "DataResponse",
    "BulkDataResponse",
    "PaginatedResponse",
    "PaginationParams",
    "PaginationInfo",
    "DateRangeParams",
    "SymbolParams",
    "MultiSymbolParams",
    "SortParams",
    "FilterParams",
    "DataQualityInfo",
    "CacheInfo",
    "MetadataInfo",
    "RefreshDataRequest",
    "BulkSymbolRequest",
    "HistoricalDataRequest",
    "PriceData",
    "FinancialMetrics",
    "SentimentData",
    # Stock schemas - Requests
    "DailyPriceRequest",
    "IntradayPriceRequest",
    "QuoteRequest",
    "BulkQuoteRequest",
    "DividendRequest",
    "SplitRequest",
    "StockSearchRequest",
    "BatchStockRequest",
    # Stock schemas - Data models
    "DailyPriceData",
    "IntradayPriceData",
    "QuoteData",
    "DividendData",
    "SplitData",
    "StockOverviewData",
    "StockSearchData",
    "MarketStatusData",
    "BatchStockStatus",
    # Stock schemas - Responses
    "DailyPriceResponse",
    "DailyPriceListResponse",
    "IntradayPriceResponse",
    "IntradayPriceListResponse",
    "QuoteResponse",
    "BulkQuoteResponse",
    "DividendListResponse",
    "SplitListResponse",
    "StockOverviewResponse",
    "StockSearchResponse",
    "MarketStatusResponse",
    "BatchStockResponse",
    # Fundamental schemas - Requests
    "CompanyOverviewRequest",
    "FinancialStatementRequest",
    "EarningsRequest",
    "BulkFundamentalRequest",
    "PeerComparisonRequest",
    # Fundamental schemas - Data models
    "CompanyOverviewData",
    "IncomeStatementData",
    "BalanceSheetData",
    "CashFlowData",
    "EarningsData",
    "FundamentalAnalysisData",
    "PeerComparisonData",
    "SectorAnalysisData",
    # Fundamental schemas - Responses
    "CompanyOverviewResponse",
    "IncomeStatementListResponse",
    "BalanceSheetListResponse",
    "CashFlowListResponse",
    "EarningsListResponse",
    "FundamentalAnalysisResponse",
    "PeerComparisonResponse",
    "SectorAnalysisResponse",
    # Economic indicator schemas - Requests
    "EconomicIndicatorRequest",
    "BulkEconomicIndicatorRequest",
    "GDPRequest",
    "InflationRequest",
    "InterestRateRequest",
    # Economic indicator schemas - Data models
    "EconomicIndicatorData",
    "GDPData",
    "InflationData",
    "InterestRateData",
    "EmploymentData",
    "ManufacturingData",
    "ConsumerSentimentData",
    "EconomicOverviewData",
    # Economic indicator schemas - Responses
    "EconomicIndicatorListResponse",
    "GDPListResponse",
    "InflationListResponse",
    "InterestRateListResponse",
    "EmploymentListResponse",
    "ManufacturingListResponse",
    "ConsumerSentimentListResponse",
    "EconomicOverviewResponse",
    # Intelligence schemas - Requests
    "NewsSentimentRequest",
    "NewsArticleRequest",
    "AnalystRatingRequest",
    "SocialSentimentRequest",
    "MarketMoodRequest",
    "OptionFlowRequest",
    "SentimentAlertRequest",
    # Intelligence schemas - Data models
    "NewsSentimentData",
    "NewsArticleData",
    "AnalystRatingData",
    "SocialSentimentData",
    "MarketMoodData",
    "OptionFlowData",
    "IntelligenceOverviewData",
    "SentimentAlertData",
    # Intelligence schemas - Responses
    "NewsSentimentResponse",
    "NewsArticleListResponse",
    "AnalystRatingListResponse",
    "SocialSentimentListResponse",
    "MarketMoodResponse",
    "OptionFlowListResponse",
    "IntelligenceOverviewResponse",
    "SentimentAlertResponse",
]
