// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
	baseUrl: `${string}://${string}` | (string & {});
};

/**
 * BacktestConfig
 * 백테스트 설정 내장 모델
 */
export type BacktestConfig = {
	/**
	 * Name
	 * 백테스트 이름
	 */
	name: string;
	/**
	 * Description
	 * 백테스트 설명
	 */
	description?: string;
	/**
	 * Start Date
	 * 시작일
	 */
	start_date: Date;
	/**
	 * End Date
	 * 종료일
	 */
	end_date: Date;
	/**
	 * Symbols
	 * 대상 심볼 목록
	 */
	symbols: Array<string>;
	/**
	 * Initial Cash
	 * 초기 자본금
	 */
	initial_cash?: number;
	/**
	 * Max Position Size
	 * 최대 포지션 크기 (비율)
	 */
	max_position_size?: number;
	/**
	 * Commission Rate
	 * 수수료율
	 */
	commission_rate?: number;
	/**
	 * Slippage Rate
	 * 슬리피지율
	 */
	slippage_rate?: number;
	/**
	 * Rebalance Frequency
	 * 리밸런싱 주기 (daily, weekly, monthly)
	 */
	rebalance_frequency?: string | null;
	/**
	 * Tags
	 * 태그
	 */
	tags?: Array<string>;
};

/**
 * BacktestCreateRequest
 * 백테스트 생성 요청
 */
export type BacktestCreateRequest = {
	/**
	 * User Id
	 */
	user_id?: string | null;
	/**
	 * Name
	 * 백테스트 이름
	 */
	name: string;
	/**
	 * Description
	 * 백테스트 설명
	 */
	description?: string;
	/**
	 * 백테스트 설정
	 */
	config: BacktestConfig;
};

/**
 * BacktestExecutionListResponse
 * 백테스트 실행 목록 응답
 */
export type BacktestExecutionListResponse = {
	/**
	 * User Id
	 */
	user_id?: string | null;
	/**
	 * Executions
	 * 실행 목록
	 */
	executions: Array<BacktestExecutionResponse>;
	/**
	 * Total
	 * 총 개수
	 */
	total: number;
};

/**
 * BacktestExecutionRequest
 * 백테스트 실행 요청
 */
export type BacktestExecutionRequest = {
	/**
	 * User Id
	 */
	user_id?: string | null;
	/**
	 * Signals
	 * 트레이딩 시그널 목록
	 */
	signals: Array<{
		[key: string]: unknown;
	}>;
};

/**
 * BacktestExecutionResponse
 * 백테스트 실행 응답
 */
export type BacktestExecutionResponse = {
	/**
	 * User Id
	 */
	user_id?: string | null;
	/**
	 * Id
	 * 실행 ID
	 */
	id: string;
	/**
	 * Backtest Id
	 * 백테스트 ID
	 */
	backtest_id: string;
	/**
	 * Execution Id
	 * 실행 ID
	 */
	execution_id: string;
	/**
	 * Start Time
	 * 실행 시작 시간
	 */
	start_time: Date;
	/**
	 * End Time
	 * 실행 종료 시간
	 */
	end_time?: Date | null;
	/**
	 * 실행 상태
	 */
	status: BacktestStatus;
	/**
	 * Portfolio Values
	 * 포트폴리오 가치 히스토리
	 */
	portfolio_values: Array<number>;
	/**
	 * Trades
	 * 거래 내역
	 */
	trades: Array<Trade>;
	/**
	 * Positions
	 * 최종 포지션
	 */
	positions: {
		[key: string]: Position;
	};
	/**
	 * Error Message
	 * 오류 메시지
	 */
	error_message?: string | null;
	/**
	 * Created At
	 * 생성 시간
	 */
	created_at: Date;
};

/**
 * BacktestListResponse
 * 백테스트 목록 응답
 */
export type BacktestListResponse = {
	/**
	 * User Id
	 */
	user_id?: string | null;
	/**
	 * Backtests
	 * 백테스트 목록
	 */
	backtests: Array<BacktestResponse>;
	/**
	 * Total
	 * 총 개수
	 */
	total: number;
};

/**
 * BacktestResponse
 * 백테스트 응답
 */
export type BacktestResponse = {
	/**
	 * User Id
	 */
	user_id?: string | null;
	/**
	 * Id
	 * 백테스트 ID
	 */
	id: string;
	/**
	 * Name
	 * 백테스트 이름
	 */
	name: string;
	/**
	 * Description
	 * 백테스트 설명
	 */
	description: string;
	/**
	 * 백테스트 설정
	 */
	config: BacktestConfig;
	/**
	 * 실행 상태
	 */
	status: BacktestStatus;
	/**
	 * Start Time
	 * 실행 시작 시간
	 */
	start_time?: Date | null;
	/**
	 * End Time
	 * 실행 종료 시간
	 */
	end_time?: Date | null;
	/**
	 * Duration Seconds
	 * 실행 시간(초)
	 */
	duration_seconds?: number | null;
	/**
	 * 성과 지표
	 */
	performance?: PerformanceMetrics | null;
	/**
	 * Created At
	 * 생성 시간
	 */
	created_at: Date;
	/**
	 * Updated At
	 * 수정 시간
	 */
	updated_at?: Date | null;
};

/**
 * BacktestStatus
 * 백테스트 상태
 */
export type BacktestStatus =
	| "pending"
	| "running"
	| "completed"
	| "failed"
	| "cancelled";

/**
 * BacktestUpdateRequest
 * 백테스트 수정 요청
 */
export type BacktestUpdateRequest = {
	/**
	 * User Id
	 */
	user_id?: string | null;
	/**
	 * Name
	 * 백테스트 이름
	 */
	name?: string | null;
	/**
	 * Description
	 * 백테스트 설명
	 */
	description?: string | null;
	/**
	 * 백테스트 설정
	 */
	config?: BacktestConfig | null;
};

/**
 * BalanceSheetData
 * 재무상태표 응답 모델
 */
export type BalanceSheetData = {
	/**
	 * Symbol
	 * 주식 심볼
	 */
	symbol: string;
	/**
	 * Fiscal Date Ending
	 * 회계연도 종료일
	 */
	fiscal_date_ending: Date;
	/**
	 * Reported Currency
	 * 보고 통화
	 */
	reported_currency?: string;
	/**
	 * Total Assets
	 * 총자산
	 */
	total_assets?: string | null;
	/**
	 * Total Current Assets
	 * 총 유동자산
	 */
	total_current_assets?: string | null;
	/**
	 * Cash And Cash Equivalents
	 * 현금 및 현금성자산
	 */
	cash_and_cash_equivalents?: string | null;
	/**
	 * Inventory
	 * 재고자산
	 */
	inventory?: string | null;
	/**
	 * Current Net Receivables
	 * 유동 순매출채권
	 */
	current_net_receivables?: string | null;
	/**
	 * Property Plant Equipment
	 * 유형자산
	 */
	property_plant_equipment?: string | null;
	/**
	 * Goodwill
	 * 영업권
	 */
	goodwill?: string | null;
	/**
	 * Intangible Assets
	 * 무형자산
	 */
	intangible_assets?: string | null;
	/**
	 * Total Liabilities
	 * 총부채
	 */
	total_liabilities?: string | null;
	/**
	 * Total Current Liabilities
	 * 총 유동부채
	 */
	total_current_liabilities?: string | null;
	/**
	 * Current Accounts Payable
	 * 유동 매입채무
	 */
	current_accounts_payable?: string | null;
	/**
	 * Current Debt
	 * 유동부채
	 */
	current_debt?: string | null;
	/**
	 * Long Term Debt
	 * 장기부채
	 */
	long_term_debt?: string | null;
	/**
	 * Total Shareholder Equity
	 * 총 자기자본
	 */
	total_shareholder_equity?: string | null;
	/**
	 * Retained Earnings
	 * 이익잉여금
	 */
	retained_earnings?: string | null;
	/**
	 * Common Stock
	 * 보통주
	 */
	common_stock?: string | null;
	/**
	 * Treasury Stock
	 * 자기주식
	 */
	treasury_stock?: string | null;
	/**
	 * Common Stock Shares Outstanding
	 * 보통주 발행주식수
	 */
	common_stock_shares_outstanding?: number | null;
};

/**
 * BalanceSheetResponse
 * 재무상태표 조회 응답 스키마
 */
export type BalanceSheetResponse = {
	/**
	 * Success
	 * 요청 성공 여부
	 */
	success?: boolean;
	/**
	 * Message
	 * 응답 메시지
	 */
	message?: string | null;
	/**
	 * Timestamp
	 * 응답 시간
	 */
	timestamp?: Date;
	/**
	 * Data
	 * 데이터 목록
	 */
	data: Array<BalanceSheetData>;
	/**
	 * 메타데이터
	 */
	metadata: MetadataInfo;
	/**
	 * Count
	 * 데이터 개수
	 */
	count: number;
};

/**
 * Body_Auth-forgot_password
 */
export type BodyAuthForgotPassword = {
	/**
	 * Email
	 */
	email: string;
};

/**
 * Body_Auth-login
 */
export type BodyAuthLogin = {
	/**
	 * Grant Type
	 */
	grant_type?: string | null;
	/**
	 * Username
	 */
	username: string;
	/**
	 * Password
	 */
	password: string;
	/**
	 * Scope
	 */
	scope?: string;
	/**
	 * Client Id
	 */
	client_id?: string | null;
	/**
	 * Client Secret
	 */
	client_secret?: string | null;
};

/**
 * Body_Auth-request_verify_token
 */
export type BodyAuthRequestVerifyToken = {
	/**
	 * Email
	 */
	email: string;
};

/**
 * Body_Auth-reset_password
 */
export type BodyAuthResetPassword = {
	/**
	 * Token
	 */
	token: string;
	/**
	 * Password
	 */
	password: string;
};

/**
 * Body_Auth-verify
 */
export type BodyAuthVerify = {
	/**
	 * Token
	 */
	token: string;
};

/**
 * CacheInfo
 * 캐시 정보
 */
export type CacheInfo = {
	/**
	 * Cached
	 * 캐시된 데이터 여부
	 */
	cached: boolean;
	/**
	 * Cache Hit
	 * 캐시 히트 여부
	 */
	cache_hit: boolean;
	/**
	 * Cache Timestamp
	 * 캐시 생성 시간
	 */
	cache_timestamp?: Date | null;
	/**
	 * Cache Ttl
	 * 캐시 TTL (초)
	 */
	cache_ttl?: number | null;
};

/**
 * CashFlowData
 * 현금흐름표 응답 모델
 */
export type CashFlowData = {
	/**
	 * Symbol
	 * 주식 심볼
	 */
	symbol: string;
	/**
	 * Fiscal Date Ending
	 * 회계연도 종료일
	 */
	fiscal_date_ending: Date;
	/**
	 * Reported Currency
	 * 보고 통화
	 */
	reported_currency?: string;
	/**
	 * Operating Cashflow
	 * 영업활동 현금흐름
	 */
	operating_cashflow?: string | null;
	/**
	 * Payments For Operating Activities
	 * 영업활동 현금지출
	 */
	payments_for_operating_activities?: string | null;
	/**
	 * Proceeds From Operating Activities
	 * 영업활동 현금수입
	 */
	proceeds_from_operating_activities?: string | null;
	/**
	 * Capital Expenditures
	 * 자본적지출
	 */
	capital_expenditures?: string | null;
	/**
	 * Cashflow From Investment
	 * 투자활동 현금흐름
	 */
	cashflow_from_investment?: string | null;
	/**
	 * Cashflow From Financing
	 * 재무활동 현금흐름
	 */
	cashflow_from_financing?: string | null;
	/**
	 * Dividend Payments
	 * 배당금 지급
	 */
	dividend_payments?: string | null;
	/**
	 * Payments For Repurchase Of Common Stock
	 * 자기주식 취득지출
	 */
	payments_for_repurchase_of_common_stock?: string | null;
	/**
	 * Change In Cash And Cash Equivalents
	 * 현금 및 현금성자산 변동
	 */
	change_in_cash_and_cash_equivalents?: string | null;
};

/**
 * CashFlowResponse
 * 현금흐름표 조회 응답 스키마
 */
export type CashFlowResponse = {
	/**
	 * Success
	 * 요청 성공 여부
	 */
	success?: boolean;
	/**
	 * Message
	 * 응답 메시지
	 */
	message?: string | null;
	/**
	 * Timestamp
	 * 응답 시간
	 */
	timestamp?: Date;
	/**
	 * Data
	 * 데이터 목록
	 */
	data: Array<CashFlowData>;
	/**
	 * 메타데이터
	 */
	metadata: MetadataInfo;
	/**
	 * Count
	 * 데이터 개수
	 */
	count: number;
};

/**
 * CompanyOverviewData
 * 기업 개요 응답 모델
 */
export type CompanyOverviewData = {
	/**
	 * Symbol
	 * 주식 심볼
	 */
	symbol: string;
	/**
	 * Name
	 * 회사명
	 */
	name: string;
	/**
	 * Exchange
	 * 거래소
	 */
	exchange: string;
	/**
	 * Sector
	 * 섹터
	 */
	sector?: string | null;
	/**
	 * Industry
	 * 산업
	 */
	industry?: string | null;
	/**
	 * Description
	 * 회사 설명
	 */
	description?: string | null;
	/**
	 * Currency
	 * 통화
	 */
	currency?: string;
	/**
	 * Country
	 * 국가
	 */
	country?: string | null;
	/**
	 * Fiscal Year End
	 * 회계연도 종료월
	 */
	fiscal_year_end?: string | null;
	/**
	 * Latest Quarter
	 * 최근 분기
	 */
	latest_quarter?: Date | null;
	/**
	 * Market Capitalization
	 * 시가총액
	 */
	market_capitalization?: string | null;
	/**
	 * Ebitda
	 * EBITDA
	 */
	ebitda?: string | null;
	/**
	 * Pe Ratio
	 * PER
	 */
	pe_ratio?: string | null;
	/**
	 * Peg Ratio
	 * PEG 비율
	 */
	peg_ratio?: string | null;
	/**
	 * Book Value
	 * 장부가치
	 */
	book_value?: string | null;
	/**
	 * Dividend Per Share
	 * 주당 배당금
	 */
	dividend_per_share?: string | null;
	/**
	 * Dividend Yield
	 * 배당 수익률 (%)
	 */
	dividend_yield?: string | null;
	/**
	 * Eps
	 * 주당 순이익
	 */
	eps?: string | null;
	/**
	 * Revenue Per Share Ttm
	 * 주당 매출(TTM)
	 */
	revenue_per_share_ttm?: string | null;
	/**
	 * Profit Margin
	 * 순이익률 (%)
	 */
	profit_margin?: string | null;
	/**
	 * Operating Margin Ttm
	 * 영업이익률(TTM) (%)
	 */
	operating_margin_ttm?: string | null;
	/**
	 * Return On Assets Ttm
	 * 총자산수익률(TTM) (%)
	 */
	return_on_assets_ttm?: string | null;
	/**
	 * Return On Equity Ttm
	 * 자기자본수익률(TTM) (%)
	 */
	return_on_equity_ttm?: string | null;
	/**
	 * Revenue Ttm
	 * 매출(TTM)
	 */
	revenue_ttm?: string | null;
	/**
	 * Gross Profit Ttm
	 * 매출총이익(TTM)
	 */
	gross_profit_ttm?: string | null;
	/**
	 * Fifty Two Week High
	 * 52주 최고가
	 */
	fifty_two_week_high?: string | null;
	/**
	 * Fifty Two Week Low
	 * 52주 최저가
	 */
	fifty_two_week_low?: string | null;
	/**
	 * Fifty Day Moving Average
	 * 50일 이동평균
	 */
	fifty_day_moving_average?: string | null;
	/**
	 * Two Hundred Day Moving Average
	 * 200일 이동평균
	 */
	two_hundred_day_moving_average?: string | null;
	/**
	 * Shares Outstanding
	 * 발행주식수
	 */
	shares_outstanding?: number | null;
	/**
	 * Beta
	 * 베타
	 */
	beta?: string | null;
	/**
	 * Analyst Target Price
	 * 목표 주가
	 */
	analyst_target_price?: string | null;
};

/**
 * CompanyOverviewResponse
 * 기업 개요 조회 응답 스키마
 */
export type CompanyOverviewResponse = {
	/**
	 * Success
	 * 요청 성공 여부
	 */
	success?: boolean;
	/**
	 * Message
	 * 응답 메시지
	 */
	message?: string | null;
	/**
	 * Timestamp
	 * 응답 시간
	 */
	timestamp?: Date;
	/**
	 * 데이터
	 */
	data: CompanyOverviewData;
	/**
	 * 메타데이터
	 */
	metadata: MetadataInfo;
};

/**
 * DashboardSummary
 * 대시보드 요약 데이터.
 */
export type DashboardSummary = {
	/**
	 * User Id
	 * 사용자 ID
	 */
	user_id: string;
	/**
	 * 포트폴리오 정보
	 */
	portfolio: PortfolioSummary;
	/**
	 * 전략 정보
	 */
	strategies: StrategySummary;
	/**
	 * 최근 활동
	 */
	recent_activity: RecentActivity;
};

/**
 * DashboardSummaryResponse
 * 대시보드 요약 응답.
 */
export type DashboardSummaryResponse = {
	/**
	 * 대시보드 데이터
	 */
	data: DashboardSummary;
	/**
	 * Message
	 * 응답 메시지
	 */
	message?: string;
};

/**
 * DataQualityInfo
 * 데이터 품질 정보
 */
export type DataQualityInfo = {
	/**
	 * Quality Score
	 * 품질 점수 (0-100)
	 */
	quality_score: string;
	/**
	 * Last Updated
	 * 마지막 업데이트 시간
	 */
	last_updated: Date;
	/**
	 * Data Source
	 * 데이터 출처
	 */
	data_source: string;
	/**
	 * Confidence Level
	 * 신뢰도 수준
	 */
	confidence_level?: string | null;
};

/**
 * EarningsData
 * 실적 발표 응답 모델
 */
export type EarningsData = {
	/**
	 * Symbol
	 * 주식 심볼
	 */
	symbol: string;
	/**
	 * Fiscal Date Ending
	 * 회계연도 종료일
	 */
	fiscal_date_ending: Date;
	/**
	 * Reported Date
	 * 발표일
	 */
	reported_date: Date;
	/**
	 * Reported Eps
	 * 발표 EPS
	 */
	reported_eps?: string | null;
	/**
	 * Estimated Eps
	 * 예상 EPS
	 */
	estimated_eps?: string | null;
	/**
	 * Surprise
	 * 서프라이즈
	 */
	surprise?: string | null;
	/**
	 * Surprise Percentage
	 * 서프라이즈 비율 (%)
	 */
	surprise_percentage?: string | null;
};

/**
 * EarningsResponse
 * 실적 데이터 조회 응답 스키마
 */
export type EarningsResponse = {
	/**
	 * Success
	 * 요청 성공 여부
	 */
	success?: boolean;
	/**
	 * Message
	 * 응답 메시지
	 */
	message?: string | null;
	/**
	 * Timestamp
	 * 응답 시간
	 */
	timestamp?: Date;
	/**
	 * Data
	 * 데이터 목록
	 */
	data: Array<EarningsData>;
	/**
	 * 메타데이터
	 */
	metadata: MetadataInfo;
	/**
	 * Count
	 * 데이터 개수
	 */
	count: number;
};

/**
 * EconomicCalendar
 * 경제 캘린더.
 */
export type EconomicCalendar = {
	/**
	 * Events
	 * 이벤트 목록
	 */
	events: Array<EconomicEvent>;
};

/**
 * EconomicCalendarResponse
 * 경제 캘린더 응답.
 */
export type EconomicCalendarResponse = {
	/**
	 * 경제 캘린더
	 */
	data: EconomicCalendar;
	/**
	 * Message
	 * 응답 메시지
	 */
	message?: string;
};

/**
 * EconomicEvent
 * 경제 이벤트.
 */
export type EconomicEvent = {
	/**
	 * Event Name
	 * 이벤트명
	 */
	event_name: string;
	/**
	 * Country
	 * 국가
	 */
	country: string;
	/**
	 * 중요도
	 */
	importance: ImportanceLevel;
	/**
	 * Actual
	 * 실제값
	 */
	actual?: number | null;
	/**
	 * Forecast
	 * 예상값
	 */
	forecast?: number | null;
	/**
	 * Previous
	 * 이전값
	 */
	previous?: number | null;
	/**
	 * Release Time
	 * 발표 시간
	 */
	release_time: Date;
	/**
	 * Currency
	 * 통화
	 */
	currency: string;
};

/**
 * ExecutionListResponse
 * Execution list response
 */
export type ExecutionListResponse = {
	/**
	 * User Id
	 */
	user_id?: string | null;
	/**
	 * Executions
	 * 실행 목록
	 */
	executions: Array<ExecutionResponse>;
	/**
	 * Total
	 * 총 개수
	 */
	total: number;
};

/**
 * ExecutionResponse
 * Execution response
 */
export type ExecutionResponse = {
	/**
	 * User Id
	 */
	user_id?: string | null;
	/**
	 * Id
	 * 실행 ID
	 */
	id: string;
	/**
	 * Strategy Id
	 * 전략 ID
	 */
	strategy_id: string;
	/**
	 * Strategy Name
	 * 전략 이름
	 */
	strategy_name: string;
	/**
	 * Symbol
	 * 심볼
	 */
	symbol: string;
	signal_type: SignalType;
	/**
	 * Signal Strength
	 * 신호 강도
	 */
	signal_strength: number;
	/**
	 * Price
	 * 가격
	 */
	price: number;
	/**
	 * Timestamp
	 * 실행 시간
	 */
	timestamp: Date;
	/**
	 * Metadata
	 * 메타데이터
	 */
	metadata?: {
		[key: string]: unknown;
	};
	/**
	 * Backtest Id
	 * 백테스트 ID
	 */
	backtest_id?: string | null;
	/**
	 * Created At
	 * 생성 시간
	 */
	created_at: Date;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
	/**
	 * Detail
	 */
	detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 * Health check response model.
 */
export type HealthResponse = {
	/**
	 * Status
	 */
	status: string;
	/**
	 * Timestamp
	 */
	timestamp: Date;
	/**
	 * Service
	 */
	service: string;
	/**
	 * Version
	 */
	version: string;
	/**
	 * Uptime
	 */
	uptime: number;
	/**
	 * Checks
	 */
	checks: {
		[key: string]: {
			[key: string]: unknown;
		};
	};
};

/**
 * HistoricalDataResponse
 */
export type HistoricalDataResponse = {
	/**
	 * Symbol
	 */
	symbol: string;
	/**
	 * Data
	 */
	data: Array<{
		[key: string]: unknown;
	}>;
	/**
	 * Count
	 */
	count: number;
	/**
	 * Start Date
	 */
	start_date?: Date | null;
	/**
	 * End Date
	 */
	end_date?: Date | null;
	/**
	 * Frequency
	 */
	frequency: string;
};

/**
 * ImportanceLevel
 * 중요도 레벨.
 */
export type ImportanceLevel = "high" | "medium" | "low";

/**
 * IncomeStatementData
 * 손익계산서 응답 모델
 */
export type IncomeStatementData = {
	/**
	 * Symbol
	 * 주식 심볼
	 */
	symbol: string;
	/**
	 * Fiscal Date Ending
	 * 회계연도 종료일
	 */
	fiscal_date_ending: Date;
	/**
	 * Reported Currency
	 * 보고 통화
	 */
	reported_currency?: string;
	/**
	 * Total Revenue
	 * 총 매출
	 */
	total_revenue?: string | null;
	/**
	 * Cost Of Revenue
	 * 매출원가
	 */
	cost_of_revenue?: string | null;
	/**
	 * Gross Profit
	 * 매출총이익
	 */
	gross_profit?: string | null;
	/**
	 * Research And Development
	 * 연구개발비
	 */
	research_and_development?: string | null;
	/**
	 * Selling General Administrative
	 * 판매관리비
	 */
	selling_general_administrative?: string | null;
	/**
	 * Operating Expenses
	 * 영업비용
	 */
	operating_expenses?: string | null;
	/**
	 * Operating Income
	 * 영업이익
	 */
	operating_income?: string | null;
	/**
	 * Interest Income
	 * 이자수익
	 */
	interest_income?: string | null;
	/**
	 * Interest Expense
	 * 이자비용
	 */
	interest_expense?: string | null;
	/**
	 * Income Before Tax
	 * 세전이익
	 */
	income_before_tax?: string | null;
	/**
	 * Income Tax Expense
	 * 법인세비용
	 */
	income_tax_expense?: string | null;
	/**
	 * Net Income
	 * 순이익
	 */
	net_income?: string | null;
	/**
	 * Basic Shares Outstanding
	 * 기본 주식수
	 */
	basic_shares_outstanding?: number | null;
	/**
	 * Diluted Shares Outstanding
	 * 희석 주식수
	 */
	diluted_shares_outstanding?: number | null;
	/**
	 * Basic Eps
	 * 기본 주당순이익
	 */
	basic_eps?: string | null;
	/**
	 * Diluted Eps
	 * 희석 주당순이익
	 */
	diluted_eps?: string | null;
};

/**
 * IncomeStatementResponse
 * 손익계산서 조회 응답 스키마
 */
export type IncomeStatementResponse = {
	/**
	 * Success
	 * 요청 성공 여부
	 */
	success?: boolean;
	/**
	 * Message
	 * 응답 메시지
	 */
	message?: string | null;
	/**
	 * Timestamp
	 * 응답 시간
	 */
	timestamp?: Date;
	/**
	 * Data
	 * 데이터 목록
	 */
	data: Array<IncomeStatementData>;
	/**
	 * 메타데이터
	 */
	metadata: MetadataInfo;
	/**
	 * Count
	 * 데이터 개수
	 */
	count: number;
};

/**
 * IntegratedBacktestRequest
 * 통합 백테스트 요청
 */
export type IntegratedBacktestRequest = {
	/**
	 * User Id
	 */
	user_id?: string | null;
	/**
	 * Name
	 * 백테스트 이름
	 */
	name: string;
	/**
	 * Description
	 * 백테스트 설명
	 */
	description?: string;
	/**
	 * Symbols
	 * 심볼 목록
	 */
	symbols: Array<string>;
	/**
	 * Start Date
	 * 시작일
	 */
	start_date: Date;
	/**
	 * End Date
	 * 종료일
	 */
	end_date: Date;
	/**
	 * Strategy Type
	 * 전략 타입
	 */
	strategy_type: string;
	/**
	 * Strategy Params
	 * 전략 매개변수
	 */
	strategy_params?: {
		[key: string]: unknown;
	};
	/**
	 * Initial Capital
	 * 초기 자본
	 */
	initial_capital?: number;
};

/**
 * IntegratedBacktestResponse
 * 통합 백테스트 응답
 */
export type IntegratedBacktestResponse = {
	/**
	 * User Id
	 */
	user_id?: string | null;
	/**
	 * Backtest Id
	 * 백테스트 ID
	 */
	backtest_id: string;
	/**
	 * Execution Id
	 * 실행 ID
	 */
	execution_id?: string | null;
	/**
	 * Result Id
	 * 결과 ID
	 */
	result_id?: string | null;
	/**
	 * 상태
	 */
	status: BacktestStatus;
	/**
	 * Message
	 * 메시지
	 */
	message: string;
	/**
	 * 성과 지표
	 */
	performance?: PerformanceMetrics | null;
	/**
	 * Start Time
	 * 시작 시간
	 */
	start_time?: Date | null;
	/**
	 * End Time
	 * 종료 시간
	 */
	end_time?: Date | null;
};

/**
 * LoginResponse
 */
export type LoginResponse = {
	/**
	 * Access Token
	 */
	access_token?: string | null;
	/**
	 * Refresh Token
	 */
	refresh_token?: string | null;
	/**
	 * Token Type
	 */
	token_type?: string | null;
	user_info: UserResponse;
};

/**
 * MetadataInfo
 * 메타데이터 정보
 */
export type MetadataInfo = {
	data_quality: DataQualityInfo;
	cache_info: CacheInfo;
	/**
	 * Processing Time Ms
	 * 처리 시간 (밀리초)
	 */
	processing_time_ms?: number | null;
};

/**
 * NewsArticle
 * 뉴스 기사.
 */
export type NewsArticle = {
	/**
	 * Title
	 * 제목
	 */
	title: string;
	/**
	 * Summary
	 * 요약
	 */
	summary: string;
	/**
	 * Source
	 * 출처
	 */
	source: string;
	/**
	 * Url
	 * URL
	 */
	url: string;
	/**
	 * Published At
	 * 발행 시간
	 */
	published_at: Date;
	/**
	 * 감정
	 */
	sentiment: SentimentType;
	/**
	 * Relevance Score
	 * 관련도 점수
	 */
	relevance_score: number;
	/**
	 * Symbols
	 * 관련 심볼들
	 */
	symbols: Array<string>;
};

/**
 * NewsFeed
 * 뉴스 피드.
 */
export type NewsFeed = {
	/**
	 * Articles
	 * 기사 목록
	 */
	articles: Array<NewsArticle>;
};

/**
 * NewsFeedResponse
 * 뉴스 피드 응답.
 */
export type NewsFeedResponse = {
	/**
	 * 뉴스 피드
	 */
	data: NewsFeed;
	/**
	 * Message
	 * 응답 메시지
	 */
	message?: string;
};

/**
 * OAuth2AuthorizeResponse
 */
export type OAuth2AuthorizeResponse = {
	/**
	 * Authorization Url
	 */
	authorization_url: string;
};

/**
 * OAuthAccount
 * Base OAuth account model.
 */
export type OAuthAccount = {
	/**
	 * Oauth Name
	 */
	oauth_name: string;
	/**
	 * Access Token
	 */
	access_token: string;
	/**
	 * Expires At
	 */
	expires_at?: number | null;
	/**
	 * Refresh Token
	 */
	refresh_token?: string | null;
	/**
	 * Account Id
	 */
	account_id: string;
	/**
	 * Account Email
	 */
	account_email: string;
};

/**
 * OrderType
 * 주문 타입
 */
export type OrderType = "MARKET" | "LIMIT" | "STOP" | "STOP_LIMIT";

/**
 * PerformanceMetrics
 * 성과 지표 내장 모델
 */
export type PerformanceMetrics = {
	/**
	 * Total Return
	 * 총 수익률
	 */
	total_return: number;
	/**
	 * Annualized Return
	 * 연환산 수익률
	 */
	annualized_return: number;
	/**
	 * Volatility
	 * 변동성
	 */
	volatility: number;
	/**
	 * Sharpe Ratio
	 * 샤프 비율
	 */
	sharpe_ratio: number;
	/**
	 * Max Drawdown
	 * 최대 낙폭
	 */
	max_drawdown: number;
	/**
	 * Total Trades
	 * 총 거래 수
	 */
	total_trades: number;
	/**
	 * Winning Trades
	 * 승리 거래 수
	 */
	winning_trades: number;
	/**
	 * Losing Trades
	 * 패배 거래 수
	 */
	losing_trades: number;
	/**
	 * Win Rate
	 * 승률
	 */
	win_rate: number;
};

/**
 * PerformanceResponse
 * Performance response
 */
export type PerformanceResponse = {
	/**
	 * User Id
	 */
	user_id?: string | null;
	/**
	 * Id
	 * 성과 ID
	 */
	id: string;
	/**
	 * Strategy Id
	 * 전략 ID
	 */
	strategy_id: string;
	/**
	 * Strategy Name
	 * 전략 이름
	 */
	strategy_name: string;
	/**
	 * Total Signals
	 * 총 신호 수
	 */
	total_signals: number;
	/**
	 * Buy Signals
	 * 매수 신호 수
	 */
	buy_signals: number;
	/**
	 * Sell Signals
	 * 매도 신호 수
	 */
	sell_signals: number;
	/**
	 * Hold Signals
	 * 보유 신호 수
	 */
	hold_signals: number;
	/**
	 * Total Return
	 * 총 수익률
	 */
	total_return?: number | null;
	/**
	 * Win Rate
	 * 승률
	 */
	win_rate?: number | null;
	/**
	 * Avg Return Per Trade
	 * 거래당 평균 수익률
	 */
	avg_return_per_trade?: number | null;
	/**
	 * Max Drawdown
	 * 최대 낙폭
	 */
	max_drawdown?: number | null;
	/**
	 * Sharpe Ratio
	 * 샤프 비율
	 */
	sharpe_ratio?: number | null;
	/**
	 * Calmar Ratio
	 * 칼마 비율
	 */
	calmar_ratio?: number | null;
	/**
	 * Volatility
	 * 변동성
	 */
	volatility?: number | null;
	/**
	 * Start Date
	 * 시작일
	 */
	start_date?: Date | null;
	/**
	 * End Date
	 * 종료일
	 */
	end_date?: Date | null;
	/**
	 * Accuracy
	 * 정확도
	 */
	accuracy?: number | null;
	/**
	 * Avg Signal Strength
	 * 평균 신호 강도
	 */
	avg_signal_strength?: number | null;
	/**
	 * Created At
	 * 생성 시간
	 */
	created_at: Date;
	/**
	 * Updated At
	 * 수정 시간
	 */
	updated_at: Date;
};

/**
 * PortfolioDataPoint
 * 포트폴리오 데이터 포인트.
 */
export type PortfolioDataPoint = {
	/**
	 * Timestamp
	 * 시간
	 */
	timestamp: Date;
	/**
	 * Portfolio Value
	 * 포트폴리오 가치
	 */
	portfolio_value: number;
	/**
	 * Pnl
	 * 손익
	 */
	pnl: number;
	/**
	 * Pnl Percentage
	 * 손익률
	 */
	pnl_percentage: number;
	/**
	 * Benchmark Value
	 * 벤치마크 가치
	 */
	benchmark_value?: number | null;
};

/**
 * PortfolioPerformance
 * 포트폴리오 성과 데이터.
 */
export type PortfolioPerformance = {
	/**
	 * Period
	 * 기간
	 */
	period: string;
	/**
	 * Data Points
	 * 데이터 포인트들
	 */
	data_points: Array<PortfolioDataPoint>;
	/**
	 * 성과 요약
	 */
	summary: PortfolioPerformanceSummary;
};

/**
 * PortfolioPerformanceResponse
 * 포트폴리오 성과 응답.
 */
export type PortfolioPerformanceResponse = {
	/**
	 * 포트폴리오 성과
	 */
	data: PortfolioPerformance;
	/**
	 * Message
	 * 응답 메시지
	 */
	message?: string;
};

/**
 * PortfolioPerformanceSummary
 * 포트폴리오 성과 요약.
 */
export type PortfolioPerformanceSummary = {
	/**
	 * Total Return
	 * 총 수익률
	 */
	total_return: number;
	/**
	 * Volatility
	 * 변동성
	 */
	volatility: number;
	/**
	 * Sharpe Ratio
	 * 샤프 비율
	 */
	sharpe_ratio: number;
	/**
	 * Max Drawdown
	 * 최대 낙폭
	 */
	max_drawdown: number;
};

/**
 * PortfolioSummary
 * 포트폴리오 요약 정보.
 */
export type PortfolioSummary = {
	/**
	 * Total Value
	 * 총 포트폴리오 가치
	 */
	total_value: number;
	/**
	 * Total Pnl
	 * 총 손익
	 */
	total_pnl: number;
	/**
	 * Total Pnl Percentage
	 * 총 손익률
	 */
	total_pnl_percentage: number;
	/**
	 * Daily Pnl
	 * 일일 손익
	 */
	daily_pnl: number;
	/**
	 * Daily Pnl Percentage
	 * 일일 손익률
	 */
	daily_pnl_percentage: number;
};

/**
 * Position
 * 포지션 정보 내장 모델
 */
export type Position = {
	/**
	 * Symbol
	 * 심볼
	 */
	symbol: string;
	/**
	 * Quantity
	 * 보유 수량
	 */
	quantity: number;
	/**
	 * Avg Price
	 * 평균 단가
	 */
	avg_price: number;
	/**
	 * Current Price
	 * 현재 가격
	 */
	current_price: number;
	/**
	 * Unrealized Pnl
	 * 미실현 손익
	 */
	unrealized_pnl: number;
	/**
	 * Realized Pnl
	 * 실현 손익
	 */
	realized_pnl?: number;
	/**
	 * First Buy Date
	 * 최초 매수일
	 */
	first_buy_date: Date;
	/**
	 * Last Update
	 * 마지막 업데이트
	 */
	last_update?: Date;
};

export type PydanticObjectId = string;

/**
 * RecentActivity
 * 최근 활동 정보.
 */
export type RecentActivity = {
	/**
	 * Trades Count Today
	 * 오늘 거래 수
	 */
	trades_count_today: number;
	/**
	 * Backtests Count Week
	 * 이번 주 백테스트 수
	 */
	backtests_count_week: number;
	/**
	 * Last Login
	 * 마지막 로그인
	 */
	last_login?: Date | null;
};

/**
 * RecentTrades
 * 최근 거래 데이터.
 */
export type RecentTrades = {
	/**
	 * Trades
	 * 거래 목록
	 */
	trades: Array<TradeItem>;
	/**
	 * 거래 요약
	 */
	summary: TradesSummary;
};

/**
 * RecentTradesResponse
 * 최근 거래 응답.
 */
export type RecentTradesResponse = {
	/**
	 * 최근 거래 데이터
	 */
	data: RecentTrades;
	/**
	 * Message
	 * 응답 메시지
	 */
	message?: string;
};

/**
 * SentimentType
 * 감정 분석 유형.
 */
export type SentimentType = "positive" | "neutral" | "negative";

/**
 * SignalType
 * 신호 타입
 */
export type SignalType = "BUY" | "SELL" | "HOLD";

/**
 * StrategyComparison
 * 전략 비교 데이터.
 */
export type StrategyComparison = {
	/**
	 * Strategies
	 * 전략 목록
	 */
	strategies: Array<StrategyPerformanceItem>;
};

/**
 * StrategyComparisonResponse
 * 전략 비교 응답.
 */
export type StrategyComparisonResponse = {
	/**
	 * 전략 비교 데이터
	 */
	data: StrategyComparison;
	/**
	 * Message
	 * 응답 메시지
	 */
	message?: string;
};

/**
 * StrategyCreateRequest
 * Strategy creation request
 */
export type StrategyCreateRequest = {
	/**
	 * User Id
	 */
	user_id?: string | null;
	/**
	 * Name
	 * 전략 이름
	 */
	name: string;
	/**
	 * 전략 타입
	 */
	strategy_type: StrategyType;
	/**
	 * Description
	 * 전략 설명
	 */
	description?: string | null;
	/**
	 * Parameters
	 * 전략 파라미터
	 */
	parameters?: {
		[key: string]: unknown;
	};
	/**
	 * Tags
	 * 태그
	 */
	tags?: Array<string>;
};

/**
 * StrategyExecuteRequest
 * Strategy execution request
 */
export type StrategyExecuteRequest = {
	/**
	 * User Id
	 */
	user_id?: string | null;
	/**
	 * Symbol
	 * 대상 심볼
	 */
	symbol: string;
	/**
	 * Market Data
	 * 시장 데이터
	 */
	market_data: {
		[key: string]: unknown;
	};
};

/**
 * StrategyFromTemplateRequest
 * Create strategy from template request
 */
export type StrategyFromTemplateRequest = {
	/**
	 * User Id
	 */
	user_id?: string | null;
	/**
	 * Name
	 * 전략 이름
	 */
	name: string;
	/**
	 * Parameter Overrides
	 * 파라미터 오버라이드
	 */
	parameter_overrides?: {
		[key: string]: unknown | null;
	} | null;
};

/**
 * StrategyListResponse
 * Strategy list response
 */
export type StrategyListResponse = {
	/**
	 * User Id
	 */
	user_id?: string | null;
	/**
	 * Strategies
	 * 전략 목록
	 */
	strategies: Array<StrategyResponse>;
	/**
	 * Total
	 * 총 개수
	 */
	total: number;
};

/**
 * StrategyPerformanceItem
 * 전략 성과 항목.
 */
export type StrategyPerformanceItem = {
	/**
	 * Strategy Id
	 * 전략 ID
	 */
	strategy_id: string;
	/**
	 * Name
	 * 전략 이름
	 */
	name: string;
	/**
	 * Type
	 * 전략 타입
	 */
	type: string;
	/**
	 * Total Return
	 * 총 수익률
	 */
	total_return: number;
	/**
	 * Win Rate
	 * 승률
	 */
	win_rate: number;
	/**
	 * Sharpe Ratio
	 * 샤프 비율
	 */
	sharpe_ratio: number;
	/**
	 * Trades Count
	 * 거래 수
	 */
	trades_count: number;
	/**
	 * Last Execution
	 * 마지막 실행
	 */
	last_execution?: Date | null;
	/**
	 * 상태
	 */
	status: StrategyStatus;
};

/**
 * StrategyResponse
 * Strategy response
 */
export type StrategyResponse = {
	/**
	 * User Id
	 */
	user_id?: string | null;
	/**
	 * Id
	 * 전략 ID
	 */
	id: string;
	/**
	 * Name
	 * 전략 이름
	 */
	name: string;
	/**
	 * 전략 타입
	 */
	strategy_type: StrategyType;
	/**
	 * Description
	 * 전략 설명
	 */
	description?: string | null;
	/**
	 * Parameters
	 * 전략 파라미터
	 */
	parameters?: {
		[key: string]: unknown;
	};
	/**
	 * Is Active
	 * 활성화 상태
	 */
	is_active: boolean;
	/**
	 * Is Template
	 * 템플릿 여부
	 */
	is_template: boolean;
	/**
	 * Created By
	 * 생성자
	 */
	created_by?: string | null;
	/**
	 * Created At
	 * 생성 시간
	 */
	created_at: Date;
	/**
	 * Updated At
	 * 수정 시간
	 */
	updated_at: Date;
	/**
	 * Tags
	 * 태그
	 */
	tags?: Array<string>;
};

/**
 * StrategyStatus
 * 전략 상태.
 */
export type StrategyStatus = "active" | "paused" | "stopped";

/**
 * StrategySummary
 * 전략 요약 정보.
 */
export type StrategySummary = {
	/**
	 * Active Count
	 * 활성 전략 수
	 */
	active_count: number;
	/**
	 * Total Count
	 * 총 전략 수
	 */
	total_count: number;
	/**
	 * Avg Success Rate
	 * 평균 성공률
	 */
	avg_success_rate: number;
	/**
	 * Best Performing
	 * 최고 성과 전략 ID
	 */
	best_performing?: string | null;
};

/**
 * StrategyType
 * 지원되는 전략 타입
 */
export type StrategyType =
	| "sma_crossover"
	| "rsi_mean_reversion"
	| "momentum"
	| "buy_and_hold";

/**
 * StrategyUpdateRequest
 * Strategy update request
 */
export type StrategyUpdateRequest = {
	/**
	 * User Id
	 */
	user_id?: string | null;
	/**
	 * Name
	 * 전략 이름
	 */
	name?: string | null;
	/**
	 * Description
	 * 전략 설명
	 */
	description?: string | null;
	/**
	 * Parameters
	 * 전략 파라미터
	 */
	parameters?: {
		[key: string]: unknown | null;
	} | null;
	/**
	 * Is Active
	 * 활성화 상태
	 */
	is_active?: boolean | null;
	/**
	 * Tags
	 * 태그
	 */
	tags?: Array<string | null> | null;
};

/**
 * TemplateCreateRequest
 * Template creation request
 */
export type TemplateCreateRequest = {
	/**
	 * User Id
	 */
	user_id?: string | null;
	/**
	 * Name
	 * 템플릿 이름
	 */
	name: string;
	/**
	 * 전략 타입
	 */
	strategy_type: StrategyType;
	/**
	 * Description
	 * 템플릿 설명
	 */
	description: string;
	/**
	 * Default Parameters
	 * 기본 파라미터
	 */
	default_parameters?: {
		[key: string]: unknown;
	};
	/**
	 * Parameter Schema
	 * 파라미터 스키마
	 */
	parameter_schema?: {
		[key: string]: unknown | null;
	} | null;
	/**
	 * Tags
	 * 태그
	 */
	tags?: Array<string>;
};

/**
 * TemplateListResponse
 * Template list response
 */
export type TemplateListResponse = {
	/**
	 * User Id
	 */
	user_id?: string | null;
	/**
	 * Templates
	 * 템플릿 목록
	 */
	templates: Array<TemplateResponse>;
	/**
	 * Total
	 * 총 개수
	 */
	total: number;
};

/**
 * TemplateResponse
 * Template response
 */
export type TemplateResponse = {
	/**
	 * User Id
	 */
	user_id?: string | null;
	/**
	 * Id
	 * 템플릿 ID
	 */
	id: string;
	/**
	 * Name
	 * 템플릿 이름
	 */
	name: string;
	/**
	 * 전략 타입
	 */
	strategy_type: StrategyType;
	/**
	 * Description
	 * 템플릿 설명
	 */
	description: string;
	/**
	 * Default Parameters
	 * 기본 파라미터
	 */
	default_parameters?: {
		[key: string]: unknown;
	};
	/**
	 * Parameter Schema
	 * 파라미터 스키마
	 */
	parameter_schema?: {
		[key: string]: unknown | null;
	} | null;
	/**
	 * Usage Count
	 * 사용 횟수
	 */
	usage_count: number;
	/**
	 * Created At
	 * 생성 시간
	 */
	created_at: Date;
	/**
	 * Updated At
	 * 수정 시간
	 */
	updated_at: Date;
	/**
	 * Tags
	 * 태그
	 */
	tags?: Array<string>;
};

/**
 * TemplateUpdateRequest
 * Template update request
 */
export type TemplateUpdateRequest = {
	/**
	 * User Id
	 */
	user_id?: string | null;
	/**
	 * Name
	 * 템플릿 이름
	 */
	name?: string | null;
	/**
	 * Description
	 * 템플릿 설명
	 */
	description?: string | null;
	/**
	 * Default Parameters
	 * 기본 파라미터
	 */
	default_parameters?: {
		[key: string]: unknown;
	} | null;
	/**
	 * Parameter Schema
	 * 파라미터 스키마
	 */
	parameter_schema?: {
		[key: string]: unknown | null;
	} | null;
	/**
	 * Tags
	 * 태그
	 */
	tags?: Array<string> | null;
};

/**
 * Trade
 * 거래 기록 내장 모델
 */
export type Trade = {
	/**
	 * Trade Id
	 * 거래 ID
	 */
	trade_id: string;
	/**
	 * Symbol
	 * 심볼
	 */
	symbol: string;
	trade_type: TradeType;
	order_type?: OrderType;
	/**
	 * Quantity
	 * 수량
	 */
	quantity: number;
	/**
	 * Price
	 * 체결 가격
	 */
	price: number;
	/**
	 * Timestamp
	 * 거래 시간
	 */
	timestamp: Date;
	/**
	 * Commission
	 * 수수료
	 */
	commission?: number;
	/**
	 * Slippage
	 * 슬리피지
	 */
	slippage?: number;
	/**
	 * Strategy Signal Id
	 * 전략 신호 ID
	 */
	strategy_signal_id?: string | null;
	/**
	 * Notes
	 * 메모
	 */
	notes?: string | null;
};

/**
 * TradeItem
 * 거래 항목.
 */
export type TradeItem = {
	/**
	 * Trade Id
	 * 거래 ID
	 */
	trade_id: string;
	/**
	 * Symbol
	 * 심볼
	 */
	symbol: string;
	/**
	 * 거래 방향
	 */
	side: TradeSide;
	/**
	 * Quantity
	 * 수량
	 */
	quantity: number;
	/**
	 * Price
	 * 가격
	 */
	price: number;
	/**
	 * Value
	 * 거래 금액
	 */
	value: number;
	/**
	 * Pnl
	 * 손익
	 */
	pnl: number;
	/**
	 * Strategy Name
	 * 전략 이름
	 */
	strategy_name: string;
	/**
	 * Timestamp
	 * 거래 시간
	 */
	timestamp: Date;
};

/**
 * TradeSide
 * 거래 방향.
 */
export type TradeSide = "buy" | "sell";

/**
 * TradeType
 * 거래 타입
 */
export type TradeType = "BUY" | "SELL";

/**
 * TradesSummary
 * 거래 요약.
 */
export type TradesSummary = {
	/**
	 * Total Trades
	 * 총 거래 수
	 */
	total_trades: number;
	/**
	 * Winning Trades
	 * 수익 거래 수
	 */
	winning_trades: number;
	/**
	 * Total Pnl
	 * 총 손익
	 */
	total_pnl: number;
};

/**
 * UserCreate
 */
export type UserCreate = {
	/**
	 * Email
	 */
	email: string;
	/**
	 * Full Name
	 */
	full_name?: string | null;
	/**
	 * Password
	 */
	password: string;
	/**
	 * Is Active
	 */
	is_active?: boolean | null;
	/**
	 * Is Superuser
	 */
	is_superuser?: boolean | null;
	/**
	 * Is Verified
	 */
	is_verified?: boolean | null;
	/**
	 * Avatar Url
	 */
	avatar_url?: string | null;
};

/**
 * UserResponse
 * Base User model.
 */
export type UserResponse = {
	/**
	 * Email
	 */
	email: string;
	/**
	 * Full Name
	 */
	full_name?: string | null;
	/**
	 * Is Active
	 */
	is_active?: boolean;
	/**
	 * Is Superuser
	 */
	is_superuser?: boolean;
	/**
	 * Is Verified
	 */
	is_verified?: boolean;
	/**
	 * Avatar Url
	 */
	avatar_url?: string | null;
	/**
	 * Oauth Accounts
	 */
	oauth_accounts?: Array<OAuthAccount>;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
	/**
	 * Password
	 */
	password?: string | null;
	/**
	 * Email
	 */
	email?: string | null;
	/**
	 * Full Name
	 */
	full_name?: string | null;
	/**
	 * Is Active
	 */
	is_active?: boolean | null;
	/**
	 * Is Superuser
	 */
	is_superuser?: boolean | null;
	/**
	 * Is Verified
	 */
	is_verified?: boolean | null;
	/**
	 * Avatar Url
	 */
	avatar_url?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
	/**
	 * Location
	 */
	loc: Array<string | number>;
	/**
	 * Message
	 */
	msg: string;
	/**
	 * Error Type
	 */
	type: string;
};

/**
 * WatchlistCreate
 * 워치리스트 생성 모델
 */
export type WatchlistCreate = {
	/**
	 * User Id
	 */
	user_id?: string | null;
	/**
	 * Name
	 */
	name: string;
	/**
	 * Symbols
	 */
	symbols: Array<string>;
	/**
	 * Description
	 */
	description?: string;
};

/**
 * WatchlistQuoteItem
 * 관심종목 시세 항목.
 */
export type WatchlistQuoteItem = {
	/**
	 * Symbol
	 * 심볼
	 */
	symbol: string;
	/**
	 * Name
	 * 회사명
	 */
	name: string;
	/**
	 * Current Price
	 * 현재가
	 */
	current_price: number;
	/**
	 * Change
	 * 변화량
	 */
	change: number;
	/**
	 * Change Percentage
	 * 변화율
	 */
	change_percentage: number;
	/**
	 * Volume
	 * 거래량
	 */
	volume: number;
	/**
	 * Market Cap
	 * 시가총액
	 */
	market_cap?: number | null;
};

/**
 * WatchlistQuotes
 * 관심종목 시세 데이터.
 */
export type WatchlistQuotes = {
	/**
	 * Symbols
	 * 심볼 목록
	 */
	symbols: Array<WatchlistQuoteItem>;
	/**
	 * Last Updated
	 * 마지막 업데이트
	 */
	last_updated: Date;
};

/**
 * WatchlistQuotesResponse
 * 관심종목 시세 응답.
 */
export type WatchlistQuotesResponse = {
	/**
	 * 관심종목 시세
	 */
	data: WatchlistQuotes;
	/**
	 * Message
	 * 응답 메시지
	 */
	message?: string;
};

/**
 * WatchlistUpdate
 * 워치리스트 업데이트 모델
 */
export type WatchlistUpdate = {
	/**
	 * User Id
	 */
	user_id?: string | null;
	/**
	 * Symbols
	 */
	symbols: Array<string>;
	/**
	 * Name
	 */
	name?: string | null;
	/**
	 * Description
	 */
	description?: string | null;
};

export type HealthHealthCheckData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/health/";
};

export type HealthHealthCheckResponses = {
	/**
	 * Successful Response
	 */
	200: HealthResponse;
};

export type HealthHealthCheckResponse =
	HealthHealthCheckResponses[keyof HealthHealthCheckResponses];

export type HealthLivenessProbeData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/health/live";
};

export type HealthLivenessProbeResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type HealthReadinessProbeData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/health/ready";
};

export type HealthReadinessProbeResponses = {
	/**
	 * Response Health-Readiness Probe
	 * Successful Response
	 */
	200: {
		[key: string]: unknown;
	};
};

export type HealthReadinessProbeResponse =
	HealthReadinessProbeResponses[keyof HealthReadinessProbeResponses];

export type AuthLoginData = {
	body: BodyAuthLogin;
	path?: never;
	query?: never;
	url: "/api/v1/auth/login";
};

export type AuthLoginErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type AuthLoginError = AuthLoginErrors[keyof AuthLoginErrors];

export type AuthLoginResponses = {
	/**
	 * Successful Response
	 */
	200: LoginResponse;
};

export type AuthLoginResponse = AuthLoginResponses[keyof AuthLoginResponses];

export type AuthLogoutData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/api/v1/auth/logout";
};

export type AuthLogoutErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type AuthLogoutError = AuthLogoutErrors[keyof AuthLogoutErrors];

export type AuthLogoutResponses = {
	/**
	 * Successful Response
	 */
	204: void;
};

export type AuthLogoutResponse = AuthLogoutResponses[keyof AuthLogoutResponses];

export type AuthRefreshTokenData = {
	body?: never;
	headers?: {
		/**
		 * X-Refresh-Token
		 */
		"X-Refresh-Token"?: string | null;
	};
	path?: never;
	query?: never;
	url: "/api/v1/auth/refresh";
};

export type AuthRefreshTokenErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type AuthRefreshTokenError =
	AuthRefreshTokenErrors[keyof AuthRefreshTokenErrors];

export type AuthRefreshTokenResponses = {
	/**
	 * Successful Response
	 */
	200: LoginResponse;
};

export type AuthRefreshTokenResponse =
	AuthRefreshTokenResponses[keyof AuthRefreshTokenResponses];

export type AuthVerifyTokenData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/api/v1/auth/token/verify";
};

export type AuthVerifyTokenErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type AuthVerifyTokenError =
	AuthVerifyTokenErrors[keyof AuthVerifyTokenErrors];

export type AuthVerifyTokenResponses = {
	/**
	 * Response Auth-Verify Token
	 * Successful Response
	 */
	200: {
		[key: string]: unknown;
	};
};

export type AuthVerifyTokenResponse =
	AuthVerifyTokenResponses[keyof AuthVerifyTokenResponses];

export type AuthRegisterData = {
	body: UserCreate;
	path?: never;
	query?: never;
	url: "/api/v1/auth/register";
};

export type AuthRegisterErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type AuthRegisterError = AuthRegisterErrors[keyof AuthRegisterErrors];

export type AuthRegisterResponses = {
	/**
	 * Successful Response
	 */
	201: UserResponse;
};

export type AuthRegisterResponse =
	AuthRegisterResponses[keyof AuthRegisterResponses];

export type AuthForgotPasswordData = {
	body: BodyAuthForgotPassword;
	path?: never;
	query?: never;
	url: "/api/v1/auth/forgot-password";
};

export type AuthForgotPasswordErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type AuthForgotPasswordError =
	AuthForgotPasswordErrors[keyof AuthForgotPasswordErrors];

export type AuthForgotPasswordResponses = {
	/**
	 * Successful Response
	 */
	202: unknown;
};

export type AuthResetPasswordData = {
	body: BodyAuthResetPassword;
	path?: never;
	query?: never;
	url: "/api/v1/auth/reset-password";
};

export type AuthResetPasswordErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type AuthResetPasswordError =
	AuthResetPasswordErrors[keyof AuthResetPasswordErrors];

export type AuthResetPasswordResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type AuthRequestVerifyTokenData = {
	body: BodyAuthRequestVerifyToken;
	path?: never;
	query?: never;
	url: "/api/v1/auth/request-verify-token";
};

export type AuthRequestVerifyTokenErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type AuthRequestVerifyTokenError =
	AuthRequestVerifyTokenErrors[keyof AuthRequestVerifyTokenErrors];

export type AuthRequestVerifyTokenResponses = {
	/**
	 * Successful Response
	 */
	202: unknown;
};

export type AuthVerifyData = {
	body: BodyAuthVerify;
	path?: never;
	query?: never;
	url: "/api/v1/auth/verify";
};

export type AuthVerifyErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type AuthVerifyError = AuthVerifyErrors[keyof AuthVerifyErrors];

export type AuthVerifyResponses = {
	/**
	 * Successful Response
	 */
	200: UserResponse;
};

export type AuthVerifyResponse = AuthVerifyResponses[keyof AuthVerifyResponses];

export type UserGetUserMeData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/api/v1/users/me";
};

export type UserGetUserMeErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type UserGetUserMeError = UserGetUserMeErrors[keyof UserGetUserMeErrors];

export type UserGetUserMeResponses = {
	/**
	 * Successful Response
	 */
	200: UserResponse;
};

export type UserGetUserMeResponse =
	UserGetUserMeResponses[keyof UserGetUserMeResponses];

export type UserUpdateUserMeData = {
	body: UserUpdate;
	path?: never;
	query?: never;
	url: "/api/v1/users/me";
};

export type UserUpdateUserMeErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type UserUpdateUserMeError =
	UserUpdateUserMeErrors[keyof UserUpdateUserMeErrors];

export type UserUpdateUserMeResponses = {
	/**
	 * Successful Response
	 */
	200: UserResponse;
};

export type UserUpdateUserMeResponse =
	UserUpdateUserMeResponses[keyof UserUpdateUserMeResponses];

export type UserDeleteUserData = {
	body?: never;
	path: {
		id: PydanticObjectId;
	};
	query?: never;
	url: "/api/v1/users/{id}";
};

export type UserDeleteUserErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type UserDeleteUserError =
	UserDeleteUserErrors[keyof UserDeleteUserErrors];

export type UserDeleteUserResponses = {
	/**
	 * Successful Response
	 */
	204: void;
};

export type UserDeleteUserResponse =
	UserDeleteUserResponses[keyof UserDeleteUserResponses];

export type UserGetUserData = {
	body?: never;
	path: {
		id: PydanticObjectId;
	};
	query?: never;
	url: "/api/v1/users/{id}";
};

export type UserGetUserErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type UserGetUserError = UserGetUserErrors[keyof UserGetUserErrors];

export type UserGetUserResponses = {
	/**
	 * Successful Response
	 */
	200: UserResponse;
};

export type UserGetUserResponse =
	UserGetUserResponses[keyof UserGetUserResponses];

export type UserUpdateUserData = {
	body: UserUpdate;
	path: {
		id: PydanticObjectId;
	};
	query?: never;
	url: "/api/v1/users/{id}";
};

export type UserUpdateUserErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type UserUpdateUserError =
	UserUpdateUserErrors[keyof UserUpdateUserErrors];

export type UserUpdateUserResponses = {
	/**
	 * Successful Response
	 */
	200: UserResponse;
};

export type UserUpdateUserResponse =
	UserUpdateUserResponses[keyof UserUpdateUserResponses];

export type OAuth2AuthorizeData = {
	body?: never;
	path: {
		/**
		 * Provider
		 */
		provider: string;
	};
	query?: {
		/**
		 * Redirect Url
		 */
		redirect_url?: string | null;
		/**
		 * State
		 */
		state?: string | null;
	};
	url: "/api/v1/oauth2/{provider}/authorize";
};

export type OAuth2AuthorizeErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type OAuth2AuthorizeError =
	OAuth2AuthorizeErrors[keyof OAuth2AuthorizeErrors];

export type OAuth2AuthorizeResponses = {
	/**
	 * Successful Response
	 */
	200: OAuth2AuthorizeResponse;
};

export type OAuth2AuthorizeResponse2 =
	OAuth2AuthorizeResponses[keyof OAuth2AuthorizeResponses];

export type OAuth2CallbackData = {
	body?: never;
	path: {
		/**
		 * Provider
		 */
		provider: string;
	};
	query: {
		/**
		 * Code
		 */
		code: string;
	};
	url: "/api/v1/oauth2/{provider}/callback";
};

export type OAuth2CallbackErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type OAuth2CallbackError =
	OAuth2CallbackErrors[keyof OAuth2CallbackErrors];

export type OAuth2CallbackResponses = {
	/**
	 * Successful Response
	 */
	200: UserResponse;
};

export type OAuth2CallbackResponse =
	OAuth2CallbackResponses[keyof OAuth2CallbackResponses];

export type UserGetMyOauthAccountsData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/api/v1/users/me/oauth-accounts";
};

export type UserGetMyOauthAccountsErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type UserGetMyOauthAccountsError =
	UserGetMyOauthAccountsErrors[keyof UserGetMyOauthAccountsErrors];

export type UserGetMyOauthAccountsResponses = {
	/**
	 * Response User-Get My Oauth Accounts
	 * Successful Response
	 */
	200: {
		[key: string]: unknown;
	};
};

export type UserGetMyOauthAccountsResponse =
	UserGetMyOauthAccountsResponses[keyof UserGetMyOauthAccountsResponses];

export type UserRemoveOauthAccountData = {
	body?: never;
	path: {
		/**
		 * Oauth Name
		 */
		oauth_name: string;
		/**
		 * Account Id
		 */
		account_id: string;
	};
	query?: never;
	url: "/api/v1/users/me/oauth-accounts/{oauth_name}/{account_id}";
};

export type UserRemoveOauthAccountErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type UserRemoveOauthAccountError =
	UserRemoveOauthAccountErrors[keyof UserRemoveOauthAccountErrors];

export type UserRemoveOauthAccountResponses = {
	/**
	 * Successful Response
	 */
	204: void;
};

export type UserRemoveOauthAccountResponse =
	UserRemoveOauthAccountResponses[keyof UserRemoveOauthAccountResponses];

export type UserGetUserOauthAccountsData = {
	body?: never;
	path: {
		user_id: PydanticObjectId;
	};
	query?: never;
	url: "/api/v1/users/{user_id}/oauth-accounts";
};

export type UserGetUserOauthAccountsErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type UserGetUserOauthAccountsError =
	UserGetUserOauthAccountsErrors[keyof UserGetUserOauthAccountsErrors];

export type UserGetUserOauthAccountsResponses = {
	/**
	 * Response User-Get User Oauth Accounts
	 * Successful Response
	 */
	200: {
		[key: string]: unknown;
	};
};

export type UserGetUserOauthAccountsResponse =
	UserGetUserOauthAccountsResponses[keyof UserGetUserOauthAccountsResponses];

export type MarketDataStockGetDailyPricesData = {
	body?: never;
	path: {
		/**
		 * Symbol
		 * 종목 심볼 (예: AAPL, TSLA)
		 */
		symbol: string;
	};
	query?: {
		/**
		 * Outputsize
		 * 데이터 크기 (compact: 최근 100일, full: 전체)
		 */
		outputsize?: string;
	};
	url: "/api/v1/market-data/stock/daily/{symbol}";
};

export type MarketDataStockGetDailyPricesErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type MarketDataStockGetDailyPricesError =
	MarketDataStockGetDailyPricesErrors[keyof MarketDataStockGetDailyPricesErrors];

export type MarketDataStockGetDailyPricesResponses = {
	/**
	 * Response Marketdata Stock-Get Daily Prices
	 * Successful Response
	 */
	200: {
		[key: string]: unknown;
	};
};

export type MarketDataStockGetDailyPricesResponse =
	MarketDataStockGetDailyPricesResponses[keyof MarketDataStockGetDailyPricesResponses];

export type MarketDataStockGetQuoteData = {
	body?: never;
	path: {
		/**
		 * Symbol
		 * 종목 심볼 (예: AAPL, TSLA)
		 */
		symbol: string;
	};
	query?: never;
	url: "/api/v1/market-data/stock/quote/{symbol}";
};

export type MarketDataStockGetQuoteErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type MarketDataStockGetQuoteError =
	MarketDataStockGetQuoteErrors[keyof MarketDataStockGetQuoteErrors];

export type MarketDataStockGetQuoteResponses = {
	/**
	 * Response Marketdata Stock-Get Quote
	 * Successful Response
	 */
	200: {
		[key: string]: unknown;
	};
};

export type MarketDataStockGetQuoteResponse =
	MarketDataStockGetQuoteResponses[keyof MarketDataStockGetQuoteResponses];

export type MarketDataStockGetIntradayDataData = {
	body?: never;
	path: {
		/**
		 * Symbol
		 * 종목 심볼 (예: AAPL, TSLA)
		 */
		symbol: string;
	};
	query?: {
		/**
		 * Interval
		 * 데이터 간격 (1min, 5min, 15min, 30min, 60min)
		 */
		interval?: string;
		/**
		 * Outputsize
		 * 데이터 크기 (compact/full)
		 */
		outputsize?: string;
	};
	url: "/api/v1/market-data/stock/intraday/{symbol}";
};

export type MarketDataStockGetIntradayDataErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type MarketDataStockGetIntradayDataError =
	MarketDataStockGetIntradayDataErrors[keyof MarketDataStockGetIntradayDataErrors];

export type MarketDataStockGetIntradayDataResponses = {
	/**
	 * Response Marketdata Stock-Get Intraday Data
	 * Successful Response
	 */
	200: {
		[key: string]: unknown;
	};
};

export type MarketDataStockGetIntradayDataResponse =
	MarketDataStockGetIntradayDataResponses[keyof MarketDataStockGetIntradayDataResponses];

export type MarketDataStockGetHistoricalDataData = {
	body?: never;
	path: {
		/**
		 * Symbol
		 * 종목 심볼 (예: AAPL, TSLA)
		 */
		symbol: string;
	};
	query?: {
		/**
		 * Start Date
		 * 시작 날짜 (YYYY-MM-DD)
		 */
		start_date?: Date | null;
		/**
		 * End Date
		 * 종료 날짜 (YYYY-MM-DD)
		 */
		end_date?: Date | null;
		/**
		 * Frequency
		 * 데이터 주기 (daily, weekly, monthly)
		 */
		frequency?: string;
	};
	url: "/api/v1/market-data/stock/historical/{symbol}";
};

export type MarketDataStockGetHistoricalDataErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type MarketDataStockGetHistoricalDataError =
	MarketDataStockGetHistoricalDataErrors[keyof MarketDataStockGetHistoricalDataErrors];

export type MarketDataStockGetHistoricalDataResponses = {
	/**
	 * Successful Response
	 */
	200: HistoricalDataResponse;
};

export type MarketDataStockGetHistoricalDataResponse =
	MarketDataStockGetHistoricalDataResponses[keyof MarketDataStockGetHistoricalDataResponses];

export type MarketDataFundamentalGetCompanyOverviewData = {
	body?: never;
	path: {
		/**
		 * Symbol
		 * 종목 심볼 (예: AAPL, TSLA)
		 */
		symbol: string;
	};
	query?: never;
	url: "/api/v1/market-data/fundamental/overview/{symbol}";
};

export type MarketDataFundamentalGetCompanyOverviewErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type MarketDataFundamentalGetCompanyOverviewError =
	MarketDataFundamentalGetCompanyOverviewErrors[keyof MarketDataFundamentalGetCompanyOverviewErrors];

export type MarketDataFundamentalGetCompanyOverviewResponses = {
	/**
	 * Successful Response
	 */
	200: CompanyOverviewResponse;
};

export type MarketDataFundamentalGetCompanyOverviewResponse =
	MarketDataFundamentalGetCompanyOverviewResponses[keyof MarketDataFundamentalGetCompanyOverviewResponses];

export type MarketDataFundamentalGetIncomeStatementData = {
	body?: never;
	path: {
		/**
		 * Symbol
		 * 종목 심볼 (예: AAPL, TSLA)
		 */
		symbol: string;
	};
	query?: {
		/**
		 * Period
		 * 보고 주기 (annual, quarterly)
		 */
		period?: string;
	};
	url: "/api/v1/market-data/fundamental/income-statement/{symbol}";
};

export type MarketDataFundamentalGetIncomeStatementErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type MarketDataFundamentalGetIncomeStatementError =
	MarketDataFundamentalGetIncomeStatementErrors[keyof MarketDataFundamentalGetIncomeStatementErrors];

export type MarketDataFundamentalGetIncomeStatementResponses = {
	/**
	 * Successful Response
	 */
	200: IncomeStatementResponse;
};

export type MarketDataFundamentalGetIncomeStatementResponse =
	MarketDataFundamentalGetIncomeStatementResponses[keyof MarketDataFundamentalGetIncomeStatementResponses];

export type MarketDataFundamentalGetBalanceSheetData = {
	body?: never;
	path: {
		/**
		 * Symbol
		 * 종목 심볼 (예: AAPL, TSLA)
		 */
		symbol: string;
	};
	query?: {
		/**
		 * Period
		 * 보고 주기 (annual, quarterly)
		 */
		period?: string;
	};
	url: "/api/v1/market-data/fundamental/balance-sheet/{symbol}";
};

export type MarketDataFundamentalGetBalanceSheetErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type MarketDataFundamentalGetBalanceSheetError =
	MarketDataFundamentalGetBalanceSheetErrors[keyof MarketDataFundamentalGetBalanceSheetErrors];

export type MarketDataFundamentalGetBalanceSheetResponses = {
	/**
	 * Successful Response
	 */
	200: BalanceSheetResponse;
};

export type MarketDataFundamentalGetBalanceSheetResponse =
	MarketDataFundamentalGetBalanceSheetResponses[keyof MarketDataFundamentalGetBalanceSheetResponses];

export type MarketDataFundamentalGetCashFlowData = {
	body?: never;
	path: {
		/**
		 * Symbol
		 * 종목 심볼 (예: AAPL, TSLA)
		 */
		symbol: string;
	};
	query?: {
		/**
		 * Period
		 * 보고 주기 (annual, quarterly)
		 */
		period?: string;
	};
	url: "/api/v1/market-data/fundamental/cash-flow/{symbol}";
};

export type MarketDataFundamentalGetCashFlowErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type MarketDataFundamentalGetCashFlowError =
	MarketDataFundamentalGetCashFlowErrors[keyof MarketDataFundamentalGetCashFlowErrors];

export type MarketDataFundamentalGetCashFlowResponses = {
	/**
	 * Successful Response
	 */
	200: CashFlowResponse;
};

export type MarketDataFundamentalGetCashFlowResponse =
	MarketDataFundamentalGetCashFlowResponses[keyof MarketDataFundamentalGetCashFlowResponses];

export type MarketDataFundamentalGetEarningsData = {
	body?: never;
	path: {
		/**
		 * Symbol
		 * 종목 심볼 (예: AAPL, TSLA)
		 */
		symbol: string;
	};
	query?: never;
	url: "/api/v1/market-data/fundamental/earnings/{symbol}";
};

export type MarketDataFundamentalGetEarningsErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type MarketDataFundamentalGetEarningsError =
	MarketDataFundamentalGetEarningsErrors[keyof MarketDataFundamentalGetEarningsErrors];

export type MarketDataFundamentalGetEarningsResponses = {
	/**
	 * Successful Response
	 */
	200: EarningsResponse;
};

export type MarketDataFundamentalGetEarningsResponse =
	MarketDataFundamentalGetEarningsResponses[keyof MarketDataFundamentalGetEarningsResponses];

export type MarketDataEconomicGetGdpDataData = {
	body?: never;
	path?: never;
	query?: {
		/**
		 * Interval
		 * 데이터 간격 (annual, quarterly)
		 */
		interval?: string;
	};
	url: "/api/v1/market-data/economic/gdp";
};

export type MarketDataEconomicGetGdpDataErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type MarketDataEconomicGetGdpDataError =
	MarketDataEconomicGetGdpDataErrors[keyof MarketDataEconomicGetGdpDataErrors];

export type MarketDataEconomicGetGdpDataResponses = {
	/**
	 * Response Marketdata Economic-Get Gdp Data
	 * Successful Response
	 */
	200: {
		[key: string]: unknown;
	};
};

export type MarketDataEconomicGetGdpDataResponse =
	MarketDataEconomicGetGdpDataResponses[keyof MarketDataEconomicGetGdpDataResponses];

export type MarketDataEconomicGetInflationDataData = {
	body?: never;
	path?: never;
	query?: {
		/**
		 * Interval
		 * 데이터 간격 (monthly, annual)
		 */
		interval?: string;
	};
	url: "/api/v1/market-data/economic/inflation";
};

export type MarketDataEconomicGetInflationDataErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type MarketDataEconomicGetInflationDataError =
	MarketDataEconomicGetInflationDataErrors[keyof MarketDataEconomicGetInflationDataErrors];

export type MarketDataEconomicGetInflationDataResponses = {
	/**
	 * Response Marketdata Economic-Get Inflation Data
	 * Successful Response
	 */
	200: {
		[key: string]: unknown;
	};
};

export type MarketDataEconomicGetInflationDataResponse =
	MarketDataEconomicGetInflationDataResponses[keyof MarketDataEconomicGetInflationDataResponses];

export type MarketDataEconomicGetInterestRatesData = {
	body?: never;
	path?: never;
	query?: {
		/**
		 * Maturity
		 * 만기 (3month, 2year, 5year, 10year, 30year)
		 */
		maturity?: string;
	};
	url: "/api/v1/market-data/economic/interest-rates";
};

export type MarketDataEconomicGetInterestRatesErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type MarketDataEconomicGetInterestRatesError =
	MarketDataEconomicGetInterestRatesErrors[keyof MarketDataEconomicGetInterestRatesErrors];

export type MarketDataEconomicGetInterestRatesResponses = {
	/**
	 * Response Marketdata Economic-Get Interest Rates
	 * Successful Response
	 */
	200: {
		[key: string]: unknown;
	};
};

export type MarketDataEconomicGetInterestRatesResponse =
	MarketDataEconomicGetInterestRatesResponses[keyof MarketDataEconomicGetInterestRatesResponses];

export type MarketDataEconomicGetEmploymentDataData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/api/v1/market-data/economic/employment";
};

export type MarketDataEconomicGetEmploymentDataErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type MarketDataEconomicGetEmploymentDataError =
	MarketDataEconomicGetEmploymentDataErrors[keyof MarketDataEconomicGetEmploymentDataErrors];

export type MarketDataEconomicGetEmploymentDataResponses = {
	/**
	 * Response Marketdata Economic-Get Employment Data
	 * Successful Response
	 */
	200: {
		[key: string]: unknown;
	};
};

export type MarketDataEconomicGetEmploymentDataResponse =
	MarketDataEconomicGetEmploymentDataResponses[keyof MarketDataEconomicGetEmploymentDataResponses];

export type MarketDataEconomicGetConsumerSentimentData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/api/v1/market-data/economic/consumer-sentiment";
};

export type MarketDataEconomicGetConsumerSentimentErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type MarketDataEconomicGetConsumerSentimentError =
	MarketDataEconomicGetConsumerSentimentErrors[keyof MarketDataEconomicGetConsumerSentimentErrors];

export type MarketDataEconomicGetConsumerSentimentResponses = {
	/**
	 * Response Marketdata Economic-Get Consumer Sentiment
	 * Successful Response
	 */
	200: {
		[key: string]: unknown;
	};
};

export type MarketDataEconomicGetConsumerSentimentResponse =
	MarketDataEconomicGetConsumerSentimentResponses[keyof MarketDataEconomicGetConsumerSentimentResponses];

export type MarketDataIntelligenceGetNewsData = {
	body?: never;
	path: {
		/**
		 * Symbol
		 * 종목 심볼 (예: AAPL, TSLA)
		 */
		symbol: string;
	};
	query?: {
		/**
		 * Topics
		 * 관심 주제 (쉼표로 구분)
		 */
		topics?: string | null;
		/**
		 * Time From
		 * 시작 날짜 (YYYY-MM-DD)
		 */
		time_from?: Date | null;
		/**
		 * Time To
		 * 종료 날짜 (YYYY-MM-DD)
		 */
		time_to?: Date | null;
		/**
		 * Limit
		 * 결과 개수 제한
		 */
		limit?: number;
	};
	url: "/api/v1/market-data/intelligence/news/{symbol}";
};

export type MarketDataIntelligenceGetNewsErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type MarketDataIntelligenceGetNewsError =
	MarketDataIntelligenceGetNewsErrors[keyof MarketDataIntelligenceGetNewsErrors];

export type MarketDataIntelligenceGetNewsResponses = {
	/**
	 * Response Marketdata Intelligence-Get News
	 * Successful Response
	 */
	200: {
		[key: string]: unknown;
	};
};

export type MarketDataIntelligenceGetNewsResponse =
	MarketDataIntelligenceGetNewsResponses[keyof MarketDataIntelligenceGetNewsResponses];

export type MarketDataIntelligenceGetSentimentAnalysisData = {
	body?: never;
	path: {
		/**
		 * Symbol
		 * 종목 심볼 (예: AAPL, TSLA)
		 */
		symbol: string;
	};
	query?: {
		/**
		 * Time Range
		 * 시간 범위 (1week, 1month, 3months, 6months)
		 */
		time_range?: string;
		/**
		 * Sources
		 * 분석 소스 (쉼표로 구분)
		 */
		sources?: string | null;
	};
	url: "/api/v1/market-data/intelligence/sentiment/{symbol}";
};

export type MarketDataIntelligenceGetSentimentAnalysisErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type MarketDataIntelligenceGetSentimentAnalysisError =
	MarketDataIntelligenceGetSentimentAnalysisErrors[keyof MarketDataIntelligenceGetSentimentAnalysisErrors];

export type MarketDataIntelligenceGetSentimentAnalysisResponses = {
	/**
	 * Response Marketdata Intelligence-Get Sentiment Analysis
	 * Successful Response
	 */
	200: {
		[key: string]: unknown;
	};
};

export type MarketDataIntelligenceGetSentimentAnalysisResponse =
	MarketDataIntelligenceGetSentimentAnalysisResponses[keyof MarketDataIntelligenceGetSentimentAnalysisResponses];

export type MarketDataIntelligenceGetAnalystRecommendationsData = {
	body?: never;
	path: {
		/**
		 * Symbol
		 * 종목 심볼 (예: AAPL, TSLA)
		 */
		symbol: string;
	};
	query?: {
		/**
		 * Time Range
		 * 시간 범위 (1month, 3months, 6months, 1year)
		 */
		time_range?: string;
		/**
		 * Brokers
		 * 증권사 리스트 (쉼표로 구분)
		 */
		brokers?: string | null;
	};
	url: "/api/v1/market-data/intelligence/analyst-recommendations/{symbol}";
};

export type MarketDataIntelligenceGetAnalystRecommendationsErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type MarketDataIntelligenceGetAnalystRecommendationsError =
	MarketDataIntelligenceGetAnalystRecommendationsErrors[keyof MarketDataIntelligenceGetAnalystRecommendationsErrors];

export type MarketDataIntelligenceGetAnalystRecommendationsResponses = {
	/**
	 * Response Marketdata Intelligence-Get Analyst Recommendations
	 * Successful Response
	 */
	200: {
		[key: string]: unknown;
	};
};

export type MarketDataIntelligenceGetAnalystRecommendationsResponse =
	MarketDataIntelligenceGetAnalystRecommendationsResponses[keyof MarketDataIntelligenceGetAnalystRecommendationsResponses];

export type MarketDataIntelligenceGetSocialSentimentData = {
	body?: never;
	path: {
		/**
		 * Symbol
		 * 종목 심볼 (예: AAPL, TSLA)
		 */
		symbol: string;
	};
	query?: {
		/**
		 * Platforms
		 * 소셜 미디어 플랫폼 (twitter,reddit,stocktwits)
		 */
		platforms?: string | null;
		/**
		 * Time Range
		 * 시간 범위 (1day, 1week, 1month)
		 */
		time_range?: string;
	};
	url: "/api/v1/market-data/intelligence/social-sentiment/{symbol}";
};

export type MarketDataIntelligenceGetSocialSentimentErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type MarketDataIntelligenceGetSocialSentimentError =
	MarketDataIntelligenceGetSocialSentimentErrors[keyof MarketDataIntelligenceGetSocialSentimentErrors];

export type MarketDataIntelligenceGetSocialSentimentResponses = {
	/**
	 * Response Marketdata Intelligence-Get Social Sentiment
	 * Successful Response
	 */
	200: {
		[key: string]: unknown;
	};
};

export type MarketDataIntelligenceGetSocialSentimentResponse =
	MarketDataIntelligenceGetSocialSentimentResponses[keyof MarketDataIntelligenceGetSocialSentimentResponses];

export type MarketDataManagementCollectCompanyInfoData = {
	body?: never;
	path: {
		/**
		 * Symbol
		 * 종목 심볼 (예: AAPL)
		 */
		symbol: string;
	};
	query?: never;
	url: "/api/v1/market-data/management/collect/company-info/{symbol}";
};

export type MarketDataManagementCollectCompanyInfoErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type MarketDataManagementCollectCompanyInfoError =
	MarketDataManagementCollectCompanyInfoErrors[keyof MarketDataManagementCollectCompanyInfoErrors];

export type MarketDataManagementCollectCompanyInfoResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type MarketDataManagementCollectMarketDataData = {
	body?: never;
	path: {
		/**
		 * Symbol
		 * 종목 심볼 (예: AAPL)
		 */
		symbol: string;
	};
	query?: {
		/**
		 * Start Date
		 * 시작일
		 */
		start_date?: Date | null;
		/**
		 * End Date
		 * 종료일
		 */
		end_date?: Date | null;
		/**
		 * Outputsize
		 * 데이터 크기 (compact/full)
		 */
		outputsize?: string;
	};
	url: "/api/v1/market-data/management/collect/market-data/{symbol}";
};

export type MarketDataManagementCollectMarketDataErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type MarketDataManagementCollectMarketDataError =
	MarketDataManagementCollectMarketDataErrors[keyof MarketDataManagementCollectMarketDataErrors];

export type MarketDataManagementCollectMarketDataResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type MarketDataManagementCollectBulkDataData = {
	body?: never;
	path?: never;
	query: {
		/**
		 * Symbols
		 * 수집할 심볼 목록
		 */
		symbols: Array<string>;
		/**
		 * Include Company Info
		 * 기업 정보 포함 여부
		 */
		include_company_info?: boolean;
		/**
		 * Include Market Data
		 * 주가 데이터 포함 여부
		 */
		include_market_data?: boolean;
	};
	url: "/api/v1/market-data/management/collect/bulk";
};

export type MarketDataManagementCollectBulkDataErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type MarketDataManagementCollectBulkDataError =
	MarketDataManagementCollectBulkDataErrors[keyof MarketDataManagementCollectBulkDataErrors];

export type MarketDataManagementCollectBulkDataResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type MarketDataManagementGetDataCoverageData = {
	body?: never;
	path: {
		/**
		 * Symbol
		 * 종목 심볼 (예: AAPL)
		 */
		symbol: string;
	};
	query?: never;
	url: "/api/v1/market-data/management/coverage/{symbol}";
};

export type MarketDataManagementGetDataCoverageErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type MarketDataManagementGetDataCoverageError =
	MarketDataManagementGetDataCoverageErrors[keyof MarketDataManagementGetDataCoverageErrors];

export type MarketDataManagementGetDataCoverageResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type MarketDataManagementGetSystemStatusData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/api/v1/market-data/management/status";
};

export type MarketDataManagementGetSystemStatusErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type MarketDataManagementGetSystemStatusError =
	MarketDataManagementGetSystemStatusErrors[keyof MarketDataManagementGetSystemStatusErrors];

export type MarketDataManagementGetSystemStatusResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type MarketDataGetMarketDataInfoData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/api/v1/market-data/";
};

export type MarketDataGetMarketDataInfoErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type MarketDataGetMarketDataInfoError =
	MarketDataGetMarketDataInfoErrors[keyof MarketDataGetMarketDataInfoErrors];

export type MarketDataGetMarketDataInfoResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type MarketDataHealthCheckData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/api/v1/market-data/health";
};

export type MarketDataHealthCheckErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type MarketDataHealthCheckError =
	MarketDataHealthCheckErrors[keyof MarketDataHealthCheckErrors];

export type MarketDataHealthCheckResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type StrategyGetStrategiesData = {
	body?: never;
	path?: never;
	query?: {
		/**
		 * Strategy Type
		 * 전략 타입 필터
		 */
		strategy_type?: StrategyType | null;
		/**
		 * Is Active
		 * 활성화 상태 필터
		 */
		is_active?: boolean | null;
		/**
		 * Is Template
		 * 템플릿 여부 필터
		 */
		is_template?: boolean | null;
		/**
		 * Limit
		 * 결과 수 제한
		 */
		limit?: number;
	};
	url: "/api/v1/strategies/strategies/";
};

export type StrategyGetStrategiesErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type StrategyGetStrategiesError =
	StrategyGetStrategiesErrors[keyof StrategyGetStrategiesErrors];

export type StrategyGetStrategiesResponses = {
	/**
	 * Successful Response
	 */
	200: StrategyListResponse;
};

export type StrategyGetStrategiesResponse =
	StrategyGetStrategiesResponses[keyof StrategyGetStrategiesResponses];

export type StrategyCreateStrategyData = {
	body: StrategyCreateRequest;
	path?: never;
	query?: never;
	url: "/api/v1/strategies/strategies/";
};

export type StrategyCreateStrategyErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type StrategyCreateStrategyError =
	StrategyCreateStrategyErrors[keyof StrategyCreateStrategyErrors];

export type StrategyCreateStrategyResponses = {
	/**
	 * Successful Response
	 */
	200: StrategyResponse;
};

export type StrategyCreateStrategyResponse =
	StrategyCreateStrategyResponses[keyof StrategyCreateStrategyResponses];

export type StrategyDeleteStrategyData = {
	body?: never;
	path: {
		/**
		 * Strategy Id
		 */
		strategy_id: string;
	};
	query?: never;
	url: "/api/v1/strategies/strategies/{strategy_id}";
};

export type StrategyDeleteStrategyErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type StrategyDeleteStrategyError =
	StrategyDeleteStrategyErrors[keyof StrategyDeleteStrategyErrors];

export type StrategyDeleteStrategyResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type StrategyGetStrategyData = {
	body?: never;
	path: {
		/**
		 * Strategy Id
		 */
		strategy_id: string;
	};
	query?: never;
	url: "/api/v1/strategies/strategies/{strategy_id}";
};

export type StrategyGetStrategyErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type StrategyGetStrategyError =
	StrategyGetStrategyErrors[keyof StrategyGetStrategyErrors];

export type StrategyGetStrategyResponses = {
	/**
	 * Successful Response
	 */
	200: StrategyResponse;
};

export type StrategyGetStrategyResponse =
	StrategyGetStrategyResponses[keyof StrategyGetStrategyResponses];

export type StrategyUpdateStrategyData = {
	body: StrategyUpdateRequest;
	path: {
		/**
		 * Strategy Id
		 */
		strategy_id: string;
	};
	query?: never;
	url: "/api/v1/strategies/strategies/{strategy_id}";
};

export type StrategyUpdateStrategyErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type StrategyUpdateStrategyError =
	StrategyUpdateStrategyErrors[keyof StrategyUpdateStrategyErrors];

export type StrategyUpdateStrategyResponses = {
	/**
	 * Successful Response
	 */
	200: StrategyResponse;
};

export type StrategyUpdateStrategyResponse =
	StrategyUpdateStrategyResponses[keyof StrategyUpdateStrategyResponses];

export type StrategyExecuteStrategyData = {
	body: StrategyExecuteRequest;
	path: {
		/**
		 * Strategy Id
		 */
		strategy_id: string;
	};
	query?: never;
	url: "/api/v1/strategies/strategies/{strategy_id}/execute";
};

export type StrategyExecuteStrategyErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type StrategyExecuteStrategyError =
	StrategyExecuteStrategyErrors[keyof StrategyExecuteStrategyErrors];

export type StrategyExecuteStrategyResponses = {
	/**
	 * Successful Response
	 */
	200: ExecutionResponse;
};

export type StrategyExecuteStrategyResponse =
	StrategyExecuteStrategyResponses[keyof StrategyExecuteStrategyResponses];

export type StrategyGetStrategyExecutionsData = {
	body?: never;
	path: {
		/**
		 * Strategy Id
		 */
		strategy_id: string;
	};
	query?: {
		/**
		 * Limit
		 * 결과 수 제한
		 */
		limit?: number;
	};
	url: "/api/v1/strategies/strategies/{strategy_id}/executions";
};

export type StrategyGetStrategyExecutionsErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type StrategyGetStrategyExecutionsError =
	StrategyGetStrategyExecutionsErrors[keyof StrategyGetStrategyExecutionsErrors];

export type StrategyGetStrategyExecutionsResponses = {
	/**
	 * Successful Response
	 */
	200: ExecutionListResponse;
};

export type StrategyGetStrategyExecutionsResponse =
	StrategyGetStrategyExecutionsResponses[keyof StrategyGetStrategyExecutionsResponses];

export type StrategyGetStrategyPerformanceData = {
	body?: never;
	path: {
		/**
		 * Strategy Id
		 */
		strategy_id: string;
	};
	query?: never;
	url: "/api/v1/strategies/strategies/{strategy_id}/performance";
};

export type StrategyGetStrategyPerformanceErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type StrategyGetStrategyPerformanceError =
	StrategyGetStrategyPerformanceErrors[keyof StrategyGetStrategyPerformanceErrors];

export type StrategyGetStrategyPerformanceResponses = {
	/**
	 * Successful Response
	 */
	200: PerformanceResponse;
};

export type StrategyGetStrategyPerformanceResponse =
	StrategyGetStrategyPerformanceResponses[keyof StrategyGetStrategyPerformanceResponses];

export type StrategyTemplateGetTemplatesData = {
	body?: never;
	path?: never;
	query?: {
		/**
		 * Strategy Type
		 * 전략 타입 필터
		 */
		strategy_type?: StrategyType | null;
	};
	url: "/api/v1/strategies/strategies/templates/";
};

export type StrategyTemplateGetTemplatesErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type StrategyTemplateGetTemplatesError =
	StrategyTemplateGetTemplatesErrors[keyof StrategyTemplateGetTemplatesErrors];

export type StrategyTemplateGetTemplatesResponses = {
	/**
	 * Successful Response
	 */
	200: TemplateListResponse;
};

export type StrategyTemplateGetTemplatesResponse =
	StrategyTemplateGetTemplatesResponses[keyof StrategyTemplateGetTemplatesResponses];

export type StrategyTemplateCreateTemplateData = {
	body: TemplateCreateRequest;
	path?: never;
	query?: never;
	url: "/api/v1/strategies/strategies/templates/";
};

export type StrategyTemplateCreateTemplateErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type StrategyTemplateCreateTemplateError =
	StrategyTemplateCreateTemplateErrors[keyof StrategyTemplateCreateTemplateErrors];

export type StrategyTemplateCreateTemplateResponses = {
	/**
	 * Successful Response
	 */
	200: TemplateResponse;
};

export type StrategyTemplateCreateTemplateResponse =
	StrategyTemplateCreateTemplateResponses[keyof StrategyTemplateCreateTemplateResponses];

export type StrategyTemplateDeleteTemplateData = {
	body?: never;
	path: {
		/**
		 * Template Id
		 */
		template_id: string;
	};
	query?: never;
	url: "/api/v1/strategies/strategies/templates/{template_id}";
};

export type StrategyTemplateDeleteTemplateErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type StrategyTemplateDeleteTemplateError =
	StrategyTemplateDeleteTemplateErrors[keyof StrategyTemplateDeleteTemplateErrors];

export type StrategyTemplateDeleteTemplateResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type StrategyTemplateGetTemplateData = {
	body?: never;
	path: {
		/**
		 * Template Id
		 */
		template_id: string;
	};
	query?: never;
	url: "/api/v1/strategies/strategies/templates/{template_id}";
};

export type StrategyTemplateGetTemplateErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type StrategyTemplateGetTemplateError =
	StrategyTemplateGetTemplateErrors[keyof StrategyTemplateGetTemplateErrors];

export type StrategyTemplateGetTemplateResponses = {
	/**
	 * Successful Response
	 */
	200: TemplateResponse;
};

export type StrategyTemplateGetTemplateResponse =
	StrategyTemplateGetTemplateResponses[keyof StrategyTemplateGetTemplateResponses];

export type StrategyTemplateUpdateTemplateData = {
	body: TemplateUpdateRequest;
	path: {
		/**
		 * Template Id
		 */
		template_id: string;
	};
	query?: never;
	url: "/api/v1/strategies/strategies/templates/{template_id}";
};

export type StrategyTemplateUpdateTemplateErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type StrategyTemplateUpdateTemplateError =
	StrategyTemplateUpdateTemplateErrors[keyof StrategyTemplateUpdateTemplateErrors];

export type StrategyTemplateUpdateTemplateResponses = {
	/**
	 * Successful Response
	 */
	200: TemplateResponse;
};

export type StrategyTemplateUpdateTemplateResponse =
	StrategyTemplateUpdateTemplateResponses[keyof StrategyTemplateUpdateTemplateResponses];

export type StrategyTemplateCreateStrategyFromTemplateData = {
	body: StrategyFromTemplateRequest;
	path: {
		/**
		 * Template Id
		 */
		template_id: string;
	};
	query?: never;
	url: "/api/v1/strategies/strategies/templates/{template_id}/create-strategy";
};

export type StrategyTemplateCreateStrategyFromTemplateErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type StrategyTemplateCreateStrategyFromTemplateError =
	StrategyTemplateCreateStrategyFromTemplateErrors[keyof StrategyTemplateCreateStrategyFromTemplateErrors];

export type StrategyTemplateCreateStrategyFromTemplateResponses = {
	/**
	 * Successful Response
	 */
	200: StrategyResponse;
};

export type StrategyTemplateCreateStrategyFromTemplateResponse =
	StrategyTemplateCreateStrategyFromTemplateResponses[keyof StrategyTemplateCreateStrategyFromTemplateResponses];

export type StrategyTemplateGetTemplateUsageStatsData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/api/v1/strategies/strategies/templates/analytics/usage-stats";
};

export type StrategyTemplateGetTemplateUsageStatsErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type StrategyTemplateGetTemplateUsageStatsError =
	StrategyTemplateGetTemplateUsageStatsErrors[keyof StrategyTemplateGetTemplateUsageStatsErrors];

export type StrategyTemplateGetTemplateUsageStatsResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type BacktestGetBacktestsData = {
	body?: never;
	path?: never;
	query?: {
		/**
		 * Status
		 * 실행 상태 필터
		 */
		status?: BacktestStatus | null;
		/**
		 * Skip
		 * 건너뛸 개수
		 */
		skip?: number;
		/**
		 * Limit
		 * 조회할 개수
		 */
		limit?: number;
	};
	url: "/api/v1/backtests/";
};

export type BacktestGetBacktestsErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type BacktestGetBacktestsError =
	BacktestGetBacktestsErrors[keyof BacktestGetBacktestsErrors];

export type BacktestGetBacktestsResponses = {
	/**
	 * Successful Response
	 */
	200: BacktestListResponse;
};

export type BacktestGetBacktestsResponse =
	BacktestGetBacktestsResponses[keyof BacktestGetBacktestsResponses];

export type BacktestCreateBacktestData = {
	body: BacktestCreateRequest;
	path?: never;
	query?: never;
	url: "/api/v1/backtests/";
};

export type BacktestCreateBacktestErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type BacktestCreateBacktestError =
	BacktestCreateBacktestErrors[keyof BacktestCreateBacktestErrors];

export type BacktestCreateBacktestResponses = {
	/**
	 * Successful Response
	 */
	200: BacktestResponse;
};

export type BacktestCreateBacktestResponse =
	BacktestCreateBacktestResponses[keyof BacktestCreateBacktestResponses];

export type BacktestDeleteBacktestData = {
	body?: never;
	path: {
		/**
		 * Backtest Id
		 */
		backtest_id: string;
	};
	query?: never;
	url: "/api/v1/backtests/{backtest_id}";
};

export type BacktestDeleteBacktestErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type BacktestDeleteBacktestError =
	BacktestDeleteBacktestErrors[keyof BacktestDeleteBacktestErrors];

export type BacktestDeleteBacktestResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type BacktestGetBacktestData = {
	body?: never;
	path: {
		/**
		 * Backtest Id
		 */
		backtest_id: string;
	};
	query?: never;
	url: "/api/v1/backtests/{backtest_id}";
};

export type BacktestGetBacktestErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type BacktestGetBacktestError =
	BacktestGetBacktestErrors[keyof BacktestGetBacktestErrors];

export type BacktestGetBacktestResponses = {
	/**
	 * Successful Response
	 */
	200: BacktestResponse;
};

export type BacktestGetBacktestResponse =
	BacktestGetBacktestResponses[keyof BacktestGetBacktestResponses];

export type BacktestUpdateBacktestData = {
	body: BacktestUpdateRequest;
	path: {
		/**
		 * Backtest Id
		 */
		backtest_id: string;
	};
	query?: never;
	url: "/api/v1/backtests/{backtest_id}";
};

export type BacktestUpdateBacktestErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type BacktestUpdateBacktestError =
	BacktestUpdateBacktestErrors[keyof BacktestUpdateBacktestErrors];

export type BacktestUpdateBacktestResponses = {
	/**
	 * Successful Response
	 */
	200: BacktestResponse;
};

export type BacktestUpdateBacktestResponse =
	BacktestUpdateBacktestResponses[keyof BacktestUpdateBacktestResponses];

export type BacktestExecuteBacktestData = {
	body: BacktestExecutionRequest;
	path: {
		/**
		 * Backtest Id
		 */
		backtest_id: string;
	};
	query?: never;
	url: "/api/v1/backtests/{backtest_id}/execute";
};

export type BacktestExecuteBacktestErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type BacktestExecuteBacktestError =
	BacktestExecuteBacktestErrors[keyof BacktestExecuteBacktestErrors];

export type BacktestExecuteBacktestResponses = {
	/**
	 * Successful Response
	 */
	200: BacktestExecutionResponse;
};

export type BacktestExecuteBacktestResponse =
	BacktestExecuteBacktestResponses[keyof BacktestExecuteBacktestResponses];

export type BacktestGetBacktestExecutionsData = {
	body?: never;
	path: {
		/**
		 * Backtest Id
		 */
		backtest_id: string;
	};
	query?: {
		/**
		 * Skip
		 * 건너뛸 개수
		 */
		skip?: number;
		/**
		 * Limit
		 * 조회할 개수
		 */
		limit?: number;
	};
	url: "/api/v1/backtests/{backtest_id}/executions";
};

export type BacktestGetBacktestExecutionsErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type BacktestGetBacktestExecutionsError =
	BacktestGetBacktestExecutionsErrors[keyof BacktestGetBacktestExecutionsErrors];

export type BacktestGetBacktestExecutionsResponses = {
	/**
	 * Successful Response
	 */
	200: BacktestExecutionListResponse;
};

export type BacktestGetBacktestExecutionsResponse =
	BacktestGetBacktestExecutionsResponses[keyof BacktestGetBacktestExecutionsResponses];

export type BacktestGetBacktestResultsData = {
	body?: never;
	path?: never;
	query?: {
		/**
		 * Backtest Id
		 * 백테스트 ID 필터
		 */
		backtest_id?: string | null;
		/**
		 * Execution Id
		 * 실행 ID 필터
		 */
		execution_id?: string | null;
		/**
		 * Skip
		 * 건너뛸 개수
		 */
		skip?: number;
		/**
		 * Limit
		 * 조회할 개수
		 */
		limit?: number;
	};
	url: "/api/v1/backtests/results/";
};

export type BacktestGetBacktestResultsErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type BacktestGetBacktestResultsError =
	BacktestGetBacktestResultsErrors[keyof BacktestGetBacktestResultsErrors];

export type BacktestGetBacktestResultsResponses = {
	/**
	 * Response Backtest-Get Backtest Results
	 * Successful Response
	 */
	200: {
		[key: string]: unknown;
	};
};

export type BacktestGetBacktestResultsResponse =
	BacktestGetBacktestResultsResponses[keyof BacktestGetBacktestResultsResponses];

export type BacktestCreateAndRunIntegratedBacktestData = {
	body: IntegratedBacktestRequest;
	path?: never;
	query?: never;
	url: "/api/v1/backtests/integrated";
};

export type BacktestCreateAndRunIntegratedBacktestErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type BacktestCreateAndRunIntegratedBacktestError =
	BacktestCreateAndRunIntegratedBacktestErrors[keyof BacktestCreateAndRunIntegratedBacktestErrors];

export type BacktestCreateAndRunIntegratedBacktestResponses = {
	/**
	 * Successful Response
	 */
	200: IntegratedBacktestResponse;
};

export type BacktestCreateAndRunIntegratedBacktestResponse =
	BacktestCreateAndRunIntegratedBacktestResponses[keyof BacktestCreateAndRunIntegratedBacktestResponses];

export type BacktestHealthCheckData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/api/v1/backtests/health";
};

export type BacktestHealthCheckErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type BacktestHealthCheckError =
	BacktestHealthCheckErrors[keyof BacktestHealthCheckErrors];

export type BacktestHealthCheckResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type BacktestGetPerformanceAnalyticsData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/api/v1/backtests/analytics/performance-stats";
};

export type BacktestGetPerformanceAnalyticsErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type BacktestGetPerformanceAnalyticsError =
	BacktestGetPerformanceAnalyticsErrors[keyof BacktestGetPerformanceAnalyticsErrors];

export type BacktestGetPerformanceAnalyticsResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type BacktestGetTradesAnalyticsData = {
	body?: never;
	path?: never;
	query?: {
		/**
		 * Execution Id
		 * 특정 실행 ID 필터
		 */
		execution_id?: string | null;
		/**
		 * Symbol
		 * 심볼 필터
		 */
		symbol?: string | null;
	};
	url: "/api/v1/backtests/analytics/trades";
};

export type BacktestGetTradesAnalyticsErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type BacktestGetTradesAnalyticsError =
	BacktestGetTradesAnalyticsErrors[keyof BacktestGetTradesAnalyticsErrors];

export type BacktestGetTradesAnalyticsResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type BacktestGetBacktestSummaryAnalyticsData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/api/v1/backtests/analytics/summary";
};

export type BacktestGetBacktestSummaryAnalyticsErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type BacktestGetBacktestSummaryAnalyticsError =
	BacktestGetBacktestSummaryAnalyticsErrors[keyof BacktestGetBacktestSummaryAnalyticsErrors];

export type BacktestGetBacktestSummaryAnalyticsResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type WatchlistListWatchlistsData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/api/v1/watchlists/";
};

export type WatchlistListWatchlistsErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type WatchlistListWatchlistsError =
	WatchlistListWatchlistsErrors[keyof WatchlistListWatchlistsErrors];

export type WatchlistListWatchlistsResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type WatchlistCreateOrUpdateWatchlistData = {
	body: WatchlistUpdate;
	path?: never;
	query?: never;
	url: "/api/v1/watchlists/";
};

export type WatchlistCreateOrUpdateWatchlistErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type WatchlistCreateOrUpdateWatchlistError =
	WatchlistCreateOrUpdateWatchlistErrors[keyof WatchlistCreateOrUpdateWatchlistErrors];

export type WatchlistCreateOrUpdateWatchlistResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type WatchlistCreateWatchlistData = {
	body: WatchlistCreate;
	path?: never;
	query?: never;
	url: "/api/v1/watchlists/create";
};

export type WatchlistCreateWatchlistErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type WatchlistCreateWatchlistError =
	WatchlistCreateWatchlistErrors[keyof WatchlistCreateWatchlistErrors];

export type WatchlistCreateWatchlistResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type WatchlistDeleteWatchlistData = {
	body?: never;
	path: {
		/**
		 * Name
		 * 워치리스트 이름
		 */
		name: string;
	};
	query?: never;
	url: "/api/v1/watchlists/{name}";
};

export type WatchlistDeleteWatchlistErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type WatchlistDeleteWatchlistError =
	WatchlistDeleteWatchlistErrors[keyof WatchlistDeleteWatchlistErrors];

export type WatchlistDeleteWatchlistResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type WatchlistGetWatchlistData = {
	body?: never;
	path: {
		/**
		 * Name
		 * 워치리스트 이름
		 */
		name: string;
	};
	query?: never;
	url: "/api/v1/watchlists/{name}";
};

export type WatchlistGetWatchlistErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type WatchlistGetWatchlistError =
	WatchlistGetWatchlistErrors[keyof WatchlistGetWatchlistErrors];

export type WatchlistGetWatchlistResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type WatchlistUpdateWatchlistData = {
	body: WatchlistUpdate;
	path: {
		/**
		 * Name
		 * 워치리스트 이름
		 */
		name: string;
	};
	query?: never;
	url: "/api/v1/watchlists/{name}";
};

export type WatchlistUpdateWatchlistErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type WatchlistUpdateWatchlistError =
	WatchlistUpdateWatchlistErrors[keyof WatchlistUpdateWatchlistErrors];

export type WatchlistUpdateWatchlistResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type WatchlistGetWatchlistCoverageData = {
	body?: never;
	path: {
		/**
		 * Name
		 * 워치리스트 이름
		 */
		name: string;
	};
	query?: never;
	url: "/api/v1/watchlists/{name}/coverage";
};

export type WatchlistGetWatchlistCoverageErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type WatchlistGetWatchlistCoverageError =
	WatchlistGetWatchlistCoverageErrors[keyof WatchlistGetWatchlistCoverageErrors];

export type WatchlistGetWatchlistCoverageResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type WatchlistSetupDefaultWatchlistData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/api/v1/watchlists/setup-default";
};

export type WatchlistSetupDefaultWatchlistErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type WatchlistSetupDefaultWatchlistError =
	WatchlistSetupDefaultWatchlistErrors[keyof WatchlistSetupDefaultWatchlistErrors];

export type WatchlistSetupDefaultWatchlistResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type DashboardGetDashboardSummaryData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/api/v1/dashboard/summary";
};

export type DashboardGetDashboardSummaryErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type DashboardGetDashboardSummaryError =
	DashboardGetDashboardSummaryErrors[keyof DashboardGetDashboardSummaryErrors];

export type DashboardGetDashboardSummaryResponses = {
	/**
	 * Successful Response
	 */
	200: DashboardSummaryResponse;
};

export type DashboardGetDashboardSummaryResponse =
	DashboardGetDashboardSummaryResponses[keyof DashboardGetDashboardSummaryResponses];

export type DashboardGetPortfolioPerformanceData = {
	body?: never;
	path?: never;
	query?: {
		/**
		 * Period
		 * 조회 기간 (1D, 1W, 1M, 3M, 6M, 1Y)
		 */
		period?: string;
		/**
		 * Granularity
		 * 데이터 간격 (hour, day, week)
		 */
		granularity?: string;
	};
	url: "/api/v1/dashboard/portfolio/performance";
};

export type DashboardGetPortfolioPerformanceErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type DashboardGetPortfolioPerformanceError =
	DashboardGetPortfolioPerformanceErrors[keyof DashboardGetPortfolioPerformanceErrors];

export type DashboardGetPortfolioPerformanceResponses = {
	/**
	 * Successful Response
	 */
	200: PortfolioPerformanceResponse;
};

export type DashboardGetPortfolioPerformanceResponse =
	DashboardGetPortfolioPerformanceResponses[keyof DashboardGetPortfolioPerformanceResponses];

export type DashboardGetStrategyComparisonData = {
	body?: never;
	path?: never;
	query?: {
		/**
		 * Limit
		 * 조회할 전략 수
		 */
		limit?: number;
		/**
		 * Sort By
		 * 정렬 기준 (return, sharpe, win_rate)
		 */
		sort_by?: string;
	};
	url: "/api/v1/dashboard/strategies/comparison";
};

export type DashboardGetStrategyComparisonErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type DashboardGetStrategyComparisonError =
	DashboardGetStrategyComparisonErrors[keyof DashboardGetStrategyComparisonErrors];

export type DashboardGetStrategyComparisonResponses = {
	/**
	 * Successful Response
	 */
	200: StrategyComparisonResponse;
};

export type DashboardGetStrategyComparisonResponse =
	DashboardGetStrategyComparisonResponses[keyof DashboardGetStrategyComparisonResponses];

export type DashboardGetRecentTradesData = {
	body?: never;
	path?: never;
	query?: {
		/**
		 * Limit
		 * 조회할 거래 수
		 */
		limit?: number;
		/**
		 * Days
		 * 조회할 일수
		 */
		days?: number;
	};
	url: "/api/v1/dashboard/trades/recent";
};

export type DashboardGetRecentTradesErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type DashboardGetRecentTradesError =
	DashboardGetRecentTradesErrors[keyof DashboardGetRecentTradesErrors];

export type DashboardGetRecentTradesResponses = {
	/**
	 * Successful Response
	 */
	200: RecentTradesResponse;
};

export type DashboardGetRecentTradesResponse =
	DashboardGetRecentTradesResponses[keyof DashboardGetRecentTradesResponses];

export type DashboardGetWatchlistQuotesData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/api/v1/dashboard/watchlist/quotes";
};

export type DashboardGetWatchlistQuotesErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type DashboardGetWatchlistQuotesError =
	DashboardGetWatchlistQuotesErrors[keyof DashboardGetWatchlistQuotesErrors];

export type DashboardGetWatchlistQuotesResponses = {
	/**
	 * Successful Response
	 */
	200: WatchlistQuotesResponse;
};

export type DashboardGetWatchlistQuotesResponse =
	DashboardGetWatchlistQuotesResponses[keyof DashboardGetWatchlistQuotesResponses];

export type DashboardGetNewsFeedData = {
	body?: never;
	path?: never;
	query?: {
		/**
		 * Limit
		 * 조회할 뉴스 수
		 */
		limit?: number;
		/**
		 * Symbols
		 * 관련 심볼 필터
		 */
		symbols?: Array<string> | null;
		/**
		 * Categories
		 * 카테고리 필터
		 */
		categories?: Array<string> | null;
	};
	url: "/api/v1/dashboard/news/feed";
};

export type DashboardGetNewsFeedErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type DashboardGetNewsFeedError =
	DashboardGetNewsFeedErrors[keyof DashboardGetNewsFeedErrors];

export type DashboardGetNewsFeedResponses = {
	/**
	 * Successful Response
	 */
	200: NewsFeedResponse;
};

export type DashboardGetNewsFeedResponse =
	DashboardGetNewsFeedResponses[keyof DashboardGetNewsFeedResponses];

export type DashboardGetEconomicCalendarData = {
	body?: never;
	path?: never;
	query?: {
		/**
		 * Days
		 * 조회할 일수
		 */
		days?: number;
		/**
		 * Importance
		 * 중요도 필터 (high, medium, low)
		 */
		importance?: Array<string> | null;
	};
	url: "/api/v1/dashboard/economic/calendar";
};

export type DashboardGetEconomicCalendarErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type DashboardGetEconomicCalendarError =
	DashboardGetEconomicCalendarErrors[keyof DashboardGetEconomicCalendarErrors];

export type DashboardGetEconomicCalendarResponses = {
	/**
	 * Successful Response
	 */
	200: EconomicCalendarResponse;
};

export type DashboardGetEconomicCalendarResponse =
	DashboardGetEconomicCalendarResponses[keyof DashboardGetEconomicCalendarResponses];
