name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --dev

      - name: Run ruff linting
        run: uv run ruff check .

      - name: Run black formatting check
        run: uv run black --check .

      - name: Run mypy type checking
        run: uv run mypy services shared

      - name: Run security check with bandit
        run: uv run bandit -r services shared

      - name: Run safety check
        run: uv run safety check

      - name: Run tests with pytest
        run: uv run pytest --cov=services --cov=shared --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
